### ISSUE TITLE
Java 6 compatibility in redline 1.1.12

### ISSUE THREAD

**Issue by quidryan** [nebula-plugins/gradle-ospackage-plugin#10]
I tried to bump to redline 1.1.12 and found out that it's not Java 6 compatible. :-( I'm willing to loose Java 6 compatibility, if we think the changes in redline are worth it.

CC @merscwog

**Comment by bmuschko** [comment]
@quidryan Now that we upgraded the Redline library, can we close this issue?

**Comment by quidryan** [comment]
I think so.
