### ISSUE TITLE
File ownership issues

### ISSUE THREAD

**Issue by Jolter** [nebula-plugins/gradle-ospackage-plugin#102]
I want my rpm to have some files owned by a non-priviliged system user, and some files owned by root. A common enough use case, I guess.

I tried to accomplish it like this:

```
buildscript {
    dependencies {
        classpath (group: 'com.netflix.nebula', name: 'gradle-ospackage-plugin', version: '2.0.3')
    }
}
apply plugin: 'os-package'
apply plugin: 'java'
ospackage {
    permissionGroup = 'mygroup'
    user = 'service'
    from ('scripts/lsb') {
         into '/etc/init.d/'
         fileMode = 0755
         permissionGroup = 'root'
         user = 'root'
    }
    from (jar.outputs.files) {
        into myPrefix + '/lib'
}
```

However, all my files end up owned by `root`, including the jar files!

If I remove the `root` owner from the lsb scripts closure, all the files are correctly owned by `service`, including the jars. How come the ownership of one copy spec "taints" the ownership of the others?

Any ideas?

Moreover, I'm having trouble even finding a workaround. If I do the below (slightly ugly) hack, all the files in the rpm (even the jars) are still owned by root!

```
ospackage {
    from ('scripts/lsb') {
         into '/etc/init.d/'
         fileMode = 0755
         permissionGroup = 'root'
         user = 'root'
    }
    from (jar.outputs.files) {
        into myPrefix + '/lib'
         permissionGroup = 'service'
         user = 'mygroup'
}
```

**Comment by Jolter** [comment]
Can anyone have a look at this? I need to deliver my rpms to customer soon...

**Comment by bmuschko** [comment]
It seems to me as if it's a bug in the Redline RPM library. We are properly passing in the user and group values to the method `org.redline_rpm.Builder.addFile` from the plugin. I guess I'd need to provide a test case to the Redline RPM library to proof that the issues lies there. Feel free to step in.

As a side note: Setting user/group for Debs seems to work fine.

**Comment by bmuschko** [comment]
I opened an [issue](https://github.com/craigwblake/redline/issues/81) for the Redline RPM project.

**Comment by sghill** [comment]
I was able to reproduce this problem with multiple `from` blocks using the property assignment syntax. Changing to the method syntax works, as shown in the test from https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/222/commits/f9d90e2a4e164f0e3ba2be02b1c322476e7e3d85
