### ISSUE TITLE
Omit description of .deb archive if not specified in build script

### ISSUE THREAD

**Issue by holgerstolzenberg** [nebula-plugins/gradle-ospackage-plugin#104]
If you leave away the 'description' within the `ospackage` DSL then the final .deb archive (within its meta information) will contain an entry 'null' below the summary. That doesn´t not look very professional.

If specifying `description = ''`, then the description will be left away completely in the final archive.

I think if the `description` is left away, it should disappear from the final package without having to explicitly set it to an empty string.

**Comment by bmuschko** [comment]
Are you talking about `SystemPackagingExtension.packageDescription` or `Project.description`?

**Comment by holgerstolzenberg** [comment]
What I am currently using is:

```groovy
ospackage {
  packageName = "any-utils"
  version = debVersion()
  release = debRelease()
  epoch = 0
  summary = "A collection of shell scripts that ease the use of the BDWH MI cluster."
  description = ''
  …
}
```

This produces the correct meta data for me. Did I overlook something?

**Comment by bmuschko** [comment]
The extension doesn't have a property called `description`. Setting `description` within the closure delegates to `Project.description`. That's why I was asking. You still have a valid point but there's no need to declare the property in the closure. Internally, the plugin uses `Project.description` if `ospackage.packageDescription` doesn't have a value.

**Comment by holgerstolzenberg** [comment]
Then that is the problem. I do not have `project.description` set, so it is `null` which causes null to be written to the .deb meta data.

I will definitely change my misconfiguration, but I still think the string `null` should be rendered to package meta data if `project.version` is missing.

**Comment by holgerstolzenberg** [comment]
Hm, setting `ospackage.packageDescription = ''` to an empty string also causes the `null` entry in the metadata.

```groovy
ospackage {
  packageName = "any-utils"
  version = debVersion()
  release = debRelease()
  epoch = 0
  summary = "A collection of shell scripts that ease the use of the BDWH MI cluster."
  packageDescription = ''
}
```

![deb-meta-data](https://cloud.githubusercontent.com/assets/282736/7349545/3505ebca-ecfa-11e4-84ee-3fcf59fb8fa4.png)
