### ISSUE TITLE
.deb changelog file

### ISSUE THREAD

**Issue by eskatos** [nebula-plugins/gradle-ospackage-plugin#109]
Debian `changelog` file is [required](https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#changelog).
I can't find a way to set one using the plugin.
Is this even possible?

As a workaround, I tried to write it to the `build/debian` directory in another task but the `debian` task delete this directory so it had no effect.

Cheers

**Comment by eskatos** [comment]
Fixed by PR #111

**Comment by bmoyles** [comment]
It's worth noting that changelog is only required when using Debian's tooling to assemble packages. Tools like dch, debuild, dpkg-buildpackage, and so forth expect it but this project bypasses all of those tools.
