### ISSUE TITLE
Create .changes file in addition to .deb file

### ISSUE THREAD

**Issue by tbroyer** [nebula-plugins/gradle-ospackage-plugin#114]
We need to have a `.changes` file generated in addition to our `.deb` for use with reprepro's `processincoming` command (upon successful build, our Jenkins jobs SCPs the generated files and call reprepro through SSH; this work great for us with [our Maven builds](https://github.com/ozwillo/ozwillo-kernel/blob/ad8333bde7227e9bd17fc5aed916e9635613358e/oasis-dist/pom.xml) using the JDeb Maven plugin, and for our Gradle builds [calling JDeb through its Ant task](https://github.com/ozwillo/ozwillo-kernel/blob/48bc9e0775574179aa48ced3fc6f426ffc0aaefd/oasis-dist/dist.gradle), or directly through its API – see tcurdt/jdeb#132).

This might actually be as easy as:
- configuring the new output file in `TaskOutputs`
- calling `makeDeb()` instead of `createDeb(Compression)`

**Comment by f-ld** [comment]
Isn't it the case (the .changes file created) with version 3.4.0? (but not in 3.2.1 for example)

**Comment by tbroyer** [comment]
It looks like 0d484c764ce72dcb33f695e5de4f1f9ccb663bc6 switched from `createDeb` to `makeDeb` which would (according to my comment above) create the `.changes` file; but the file isn't declared as a task output (so won't be cleaned for example).

There's still this TODO in the code too:
https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/bdd55ffe4e8a2120e6fdc75d1878d1d5f360c34f/src/main/groovy/com/netflix/gradle/plugins/deb/DebCopyAction.groovy#L292-L294

(BTW, I long switched to using JDeb without the nebula plugin; I might switch back if this –and #84– is correctly fixed)
