### ISSUE TITLE
Support directory() construct for Debian packages

### ISSUE THREAD

**Issue by tbroyer** [nebula-plugins/gradle-ospackage-plugin#115]
The `directory()` construct (see #14) only works for RPMs (despite being available on the `Deb` task – because of inheritance).

It would however map quite nicely to the `DataProducerPathTemplate` from JDeb. This is what I use currently, calling JDeb directly from my build script rather than using the ospackage plugin (see tcurdt/jdeb#132)

**Comment by bmuschko** [comment]
@tbroyer Would you be interested in providing a pull request for this?

**Comment by tbroyer** [comment]
This has apparently been released in 3.4.0.
