### ISSUE TITLE
OSPackage Plugin Doesn't Work in JDK1.6

### ISSUE THREAD

**Issue by ngutzmann** [nebula-plugins/gradle-ospackage-plugin#117]
There are some functions which are new in Java1.7 that are being used in the DebPackageNameAttributeValidator class (specifically [isAlphabetic](http://docs.oracle.com/javase/7/docs/api/java/lang/Character.html#isAlphabetic(int))). Additionally when I try to compile this plugin on my own the nebula plguin-plugin jar was built with java 1.7 and so is not compatible. I would like to use the 2.4 branch of the ospackage plugin.

**Comment by ngutzmann** [comment]
@thomashw You'll be interested in this issue

**Comment by rspieldenner** [comment]
We have no plans of supporting JDK 1.6. 1.7 has been end of lifed as of April 2015 so we're definitely not going to go out of our way for jdk 1.6. We have no current plans to stop JDK 1.7 support, but won't guarantee a date.

The 2.4 branches are waiting for me to finish rewriting our publishing plugin which is broken in gradle 2.3/2.4.
