### ISSUE TITLE
fileType CONFIG | NOREPLACE not working for deb pakaging

### ISSUE THREAD

**Issue by bedge** [nebula-plugins/gradle-ospackage-plugin#118]
Using:

```
    from('src/etc) {
        fileType = CONFIG | NOREPLACE
        into '/etc`
    }
```

The modified conf file file is silently overwritten on installation.

Is there something else I need to do to make this work?

I'm using gradle 2.3, plugin version 2.2.6.

**Comment by twwwt** [comment]
Dito. Observed using Gradle 2.5, plugin version 2.2.6.

**Comment by bedge** [comment]
After pulling down the source and digging around I realized that one needs to use:
```
        configurationFile('/etc/myapp')
```
That works, but it begs the question, what does 
```
        fileType = CONFIG | NOREPLACE
```
do?

**Comment by partyzan** [comment]
Bumped into this issue as well. Weird thing is that it works for RPM packaging (we use both).

@bedge can you provide an example on how you used `configurationFile` ? Can you do that for a folder ? 

Thanks!

**Comment by bedge** [comment]
Here's how I used it to flag multiple files as conffiles:
```
	configurationFile =
		"/etc/default/myapp.conf\n" +
	 	"/etc/nim/myapp.properties"
```
Yeah, took me a while to stumble on that syntax.
Not sure if you can spec a folder.

**Comment by kyshnirev** [comment]
I'm using 
```
    plugins {
        id 'nebula.deb' version '4.3.0'
    }
    ....
    from('src/main/conf') {
        fileType CONFIG | NOREPLACE
        into 'conf'
    }
```
and have error "No signature of method: org.redline_rpm.payload.Directive.or() ..."
I have seen at https://github.com/craigwblake/redline/blob/master/src/main/java/org/redline_rpm/payload/Directive.java
and found: it is already dose not have method or() ! =)
but it have method `set( int )`
I use it like this:
```
    from('src/main/conf') {
        fileType CONFIG.set(NOREPLACE.flag()) // CONFIG | NOREPLACE
        into 'conf'
    }
```
Not looks good, but it works fine. I think Directive.java need copy-method `or( directive )`

**Comment by vutny** [comment]
This appears to be still an issue. I used plugin version `4.4.0` with Gradle 3.2.1, and this does not work for DEB packages:
```
fileType CONFIG.set(NOREPLACE.flag())
```

But ` configurationFile` trick does.

By the way, I've discovered that you just can't get list of files **marked as configs** from `*.deb` file, it must be installed into an operating system.
When do: `dpkg-query --showformat='${Conffiles}\n' --show pkg-name`

**Comment by bedge** [comment]
@kyshnirev Nice work, but are users expected to guess that?
This really belongs in the docs as an example.

**Comment by vutny** [comment]
So, maybe at least we should update Wiki article(s) with known workaround?

**Comment by chhex** [comment]
As of gradle Version: 4.10.3
And plugin Version : 5.2.0
The NOREPLACE Option doesn't work  and none of the above "workarounds" also for neblua.rpm

**Comment by aburmeis** [comment]
This is still not working and the Test from #326 is not working as it only checks if each line is either the file of the configurationFile entry or the one of the one makred with fileType CONFIG but not if there are two entries at all.
