### ISSUE TITLE
control pre/post inst/rm template docs and/or tempate disable switch for non-bash scripts

### ISSUE THREAD

**Issue by bedge** [nebula-plugins/gradle-ospackage-plugin#119]
I see that this plugin does some interesting things to one's pre/post inst/rm scripts via templates.
Are there any docs on this? 
Specifically, what is expected of the user's pre/post inst/rm script such that it meshes well with the template?

Or, is there a way to disable this so that one can include non-standard scripts, ie python or something other than shell?

**Comment by beneboy** [comment]
I have run into the same issue, case in point is that only the install argument for Debian preinst script gets called.

As a workaround, I have created a installUtils script that contains just:

            ;;
    esac

This closes the initial case statement that the plugin generates. Then, at the end of my preinst script I added:

    case "$1" in
        install)

This re-opens the case statement that the plugin script will automatically close.

While this doesn't let you include a pre/postinst (or other) script in another language (must still be sh only) it is a workaround for shell scripts until the option to include the script verbatim is included.

**Comment by scotte** [comment]
It would be much nicer to just be able to supply fully formed preinst/postinst/etc scripts. I ran into this recently when I noticed preinst only has provision for an install, but I needed to take action on an upgrade. I was able to hack it by creating a script fragment that looks like the following, but it's less than ideal (and not clear what it does for anyone looking at this file, versus extracting the generated file from the resulting .deb package):

```
# Do stuff here for install
        ;;
    upgrade)
        # Do stuff here for upgrade
```
(The spacing looks odd in this fragment is well, but it ends up right in the generated script. The spacing doesn't matter aside from readability in the generated script, but for complex scripts, consistent formatting is easier to debug).

There are a lot more actions that these control files can support: https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html - having a more flexible method for this plugin would be ideal - the option of providing a fully-formed file would be preferable over generated files from  templates.

**Comment by bedge** [comment]
I have to agree. While it's nice to DRY repetitive "install" boilerplate case statements, in this case it's a hindrance more than a benefit as it doesn't support all of the other use cases without some non-intuitive workarounds.
I'd vote for removing it, but it would probably have to be the non-default option so as to not break everything that's relying on it. 
Perhaps add a 
```
ospackage {
	wrapMaintainerScripts = false
}
```
as an option.

**Comment by bedge** [comment]
Just to resurrect this issue  -  Any chance of an option to disable this maintainer script wrapping feature?
1) can't use anything except bin/sh, so bash, python, etc are out.
2) can't specify options for different maintainer args, ie: install, configure, etc.
3) can't use shell functions inside maintainer scripts because it's illegal to put a function between case & esac, which is where this stuff ends up.
4) it just makes things harder.
Disabling this feature, or providing an "off" switch, would make life much easier.

**Comment by sghill** [comment]
@bedge @scotte @beneboy This plugin now supports providing the complete maintainer script file with the `*File` directives documented [here](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin#scripts). Could you confirm this works for your use case?

**Comment by bedge** [comment]
Confirmed the File* works as an option.

ie:
```
        installUtils file('deb/control/control-utils.sh')
        postInstall file('deb/control/postinst')
        preUninstall file('deb/control/prerm')
        postUninstall file('deb/control/postrm')
```
becomes:
```
        postInstallFile file('deb/control/postinst')
        preUninstallFile file('deb/control/prerm')
        postUninstallFile file('deb/control/postrm')
```


At the risk of the "new rope" complaint though, something in between would be nice where you could still use the installUtils for injecting common code.
ie, if installUtils is defined, prepend *File with it, otherwise just use it as-is.
