### ISSUE TITLE
Could not find method requires()

### ISSUE THREAD

**Issue by Trancelic** [nebula-plugins/gradle-ospackage-plugin#121]
Use gradle 2.5 and gradle-ospackage-plugin 2.2.6.

I can not set required packages. If use requires(String packageName) it is works, but use requires(String packageName, String version) method it not worked. On console wrote:

Could not find method requires()

**Comment by DanielThomas** [comment]
The method is `Dependency requires(String packageName, String version, int flag)`, the default flag being `0`.
