### ISSUE TITLE
rpm does not include updated scripts content

### ISSUE THREAD

**Issue by DALDEI** [nebula-plugins/gradle-ospackage-plugin#122]
Create a gradle script that has scripts as per the example (scripts/rpm/preInstall.sh
```sh
gradle rpmBuild
```
Check the scripts in the rpm 
```sh
rpm -qpl --scripts *.rpm
```
Edit one of the scripts and rebuild
```sh
gradle rpmBuild
```
Check the scripts, they have not changed
```sh
rpm -qpl --scripts *.rpm
```
Clean gradle cache
```sh
gradle clean
gradle rpmBuild
rpm -qpl --scripts *.rpm
```
Now they have changed

**Comment by DanielThomas** [comment]
Gradle mustn't be aware of that input, so it considers the `Deb` task to be up to date. Gitter is an easier way to reach us for questions, so follow the badge in the README if you still need help with this.
