### ISSUE TITLE
How to require A or require B?

### ISSUE THREAD

**Issue by adamretter** [nebula-plugins/gradle-ospackage-plugin#125]
For creating an RPM when installing onto a Linux CentOS system, I want to be able to say that my application requires either OpenJDK or Oracles's JDK, for example something like:

```
requires('zulu-8', '8.8.0', GREATER | EQUAL) || requires('ora-jdk18', '1.8', GREATER | EQUAL)
```

Any idea how to achieve this?

**Comment by cwalker67** [comment]
@adamretter - if you have control over both A and B, you can use [virtual packages](http://www.rpm.org/max-rpm/s1-rpm-depend-manual-dependencies.html)

for example:
* A `provides('unicorn')`
* B `provides('unicorn')`
* C `requires('unicorn')`

so unless you have repackaged the jdk rpms this probably won't help as I don't believe the creators of those rpms were kind enough to provide a common virtual package like (jdk-1.8).

if you don't mind skirting the way rpm would have you work, you might could use a rpm preinstall script to check for the existence of one of the two jdks and fail the install if they are missing.
