### ISSUE TITLE
Unable to use 'user' in ospackage

### ISSUE THREAD

**Issue by cwalker67** [nebula-plugins/gradle-ospackage-plugin#13]
when copying from ospackage
```
ospackage {    
    from ('conf') {
        user 'tomcat'
        permissionGroup 'tomcat'
        into '/usr/share/apache-tomcat-7.0.47/conf'    
    }
}
```
the 'user' seems to be ignored when installing a created RPM and i see the following:
```
warning: user cwalker does not exist - using root)
```

This doesn't occur if i move the 'from' config into the 'buildRpm' task

**Comment by bmuschko** [comment]
@cwalker67 Does the solution proposed by @elvenfighter work for you? If yes, can we close the issue?

**Comment by elvenfighter** [comment]
@bmushko, the problem actually exists: the ospackage plugin assigns incorrect owner to file (root to /etc/some_file instead of my_user in my case)

**Comment by bmuschko** [comment]
Please see issue #102.

**Comment by cwalker67** [comment]
@bmuschko - as @elvenfighter mentioned, the problem does still exist.  I was already creating the user in a preinstall script.  as a workaround, i've found that setting the user in the "buildRpm" config block seems to work for me

**Comment by bmuschko** [comment]
We know that the issue still exists. IMHO it's an issue with the Redline library. Please see the test cases in this [commit](https://github.com/nebula-plugins/gradle-ospackage-plugin/commit/a656165ebff99f1c260c237f277d6a041d743faf). Could you please point out how you made it work and what version of the plugin you are using?

**Comment by cwalker67** [comment]
No problem, I'll give a full example.  I have some projects that for various (poor) reasons are stuck using an old 1.X version of gradle (1.11 to be exact) and therefore using a 1.X version of the plugin.  I created this test with the latest 1.X version (1.12.8).  

**BTW - this issue does NOT appear to exist in the 2.X releases of the plugin**

*scripts/rpm/preInstall.sh*
```
/usr/sbin/groupadd -r foo 2>/dev/null || :
/usr/sbin/useradd -c "foo bar" -g wildfly -s /sbin/nologin -r  foo 2>/dev/null || :
```

*scripts/rpm/postUninstall.sh*
```
/usr/sbin/userdel -r foo 2>/dev/null || :
/usr/bin/groupdel foo 2>/dev/null || :
```

*build.gradle*
```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.netflix.nebula:gradle-ospackage-plugin:1.12.8'
    }
}

apply plugin: 'os-package'

repositories {
    mavenCentral()
}

configurations {
    test
}

dependencies {
    test 'org.apache.anakia:anakia:1.0@pom'
}

group = 'org.test.package'
version = "1.0.0"

ospackage {
    os = LINUX
    arch = NOARCH
    from(configurations.test.getSingleFile()) {
        user 'foo'
        permissionGroup 'foo'
        into('/opt/foo/bin')
    } 
}

task fooRpm(type: Rpm) {
    preInstall = file('scripts/rpm/preInstall.sh')
    postUninstall = file('scripts/rpm/postUninstall.sh')

    packageName 'foo'
}
```

Installing the file `foo-1.0.0.noarch.rpm` will result in
```
 Installing : foo-1.0.0-.noarch                                                                               1/1
warning: user cwalker does not exist - using root
warning: user cwalker does not exist - using root
warning: user cwalker does not exist - using root
  Verifying  : foo-1.0.0-.noarch                                                                               1/1
```

as a workaround, moving the `from` block from `ospackage` to `buildRpm`:
*build.gradle*
```
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.netflix.nebula:gradle-ospackage-plugin:1.12.8'
    }
}

apply plugin: 'os-package'

repositories {
    mavenCentral()
}

configurations {
    test
}

dependencies {
    test 'org.apache.anakia:anakia:1.0@pom'
}

group = 'org.test.package'
version = "1.0.0"

ospackage {
    os = LINUX
    arch = NOARCH
}

task fooRpm(type: Rpm) {
    preInstall = file('scripts/rpm/preInstall.sh')
    postUninstall = file('scripts/rpm/postUninstall.sh')
    packageName 'foo'

    from(configurations.test.getSingleFile()) {
        user 'foo'
        permissionGroup 'foo'
        into('/opt/foo/bin')
    } 
}
```

installs properly

**Comment by cwalker67** [comment]
Sorry, didn't mean to close the issue.  I was a little too fast on the clicker finder ;)

**Comment by bmuschko** [comment]
@cwalker67 Thanks for verifying that it works with the Gradle 2.x version of the plugin. Unfortunately, we are not planning to back port any fixes. You'll need to upgrade your Gradle and plugin version.

**Comment by rspieldenner** [comment]
@cwalker67 if you want to backport any of the changes we would release it
though.

On Thu, Jun 18, 2015 at 10:05 AM, Benjamin Muschko <notifications@github.com
