### ISSUE TITLE
support %posttrans and %pretrans

### ISSUE THREAD

**Issue by jnaous** [nebula-plugins/gradle-ospackage-plugin#145]
Thanks for opensourcing and maintaining this plugin. Can I make a request? Can you please add support for %posttrans and %pretrans for RPM? These are important in upgrade scenarios.

**Comment by rspieldenner** [comment]
We do not currently need these extra fields internally so adding them will be very low priority. We welcome pull requests.

**Comment by dwendelen** [comment]
I added these, but travis is rejecting the pull request for a reason I can not explain

**Comment by colindean** [comment]
@dwendelen's PR is #163

**Comment by colindean** [comment]
My team is interested in having this and might devote someone to making it happen.

**Comment by dwendelen** [comment]
I created another identical pull request ( #171 ) replacing PR #163. But unfortunately travis crashed on that one as well (error 137)

**Comment by dwendelen** [comment]
PR #171 is ready to be merged

**Comment by nadavc** [comment]
Closing issue as #171 is merged and released :+1:
