### ISSUE TITLE
sticky bit on files and directories

### ISSUE THREAD

**Issue by abedwardsw** [nebula-plugins/gradle-ospackage-plugin#152]
From what I can tell using the sticky bit umask does not seem to work.   When using a umask such as 2775 I do not get the expected results.   Could anyone confirm if they are using sticky bit successfully?

I had a quick glance at the code, looks like it might require a change when dealing with the cpio image.

**Comment by oesolutions** [comment]
Perhaps the literal values you are using are not octal? 2775 is not the same as 02775.

**Comment by abedwardsw** [comment]
Thanks for the reply, figured this out a while ago but forgot to update this ticket.  You hit the nail on the head.  Thanks again

**Comment by gallardo** [comment]
I also had the same problem misled by [the examples in the doc](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/RPM-Plugin#directories)
