### ISSUE TITLE
Recent versions of gradle-ospackage-plugin hold final RPM open if using Gradle daemon

### ISSUE THREAD

**Issue by novasbc** [nebula-plugins/gradle-ospackage-plugin#153]
I was testing moving from plugin v2.2.6 -> v3.4.0, and I noticed I couldn't delete the RPM packages, or open them with 7Zip (see below) until I closed my command prompt that I had executed Gradle from.

![image](https://cloud.githubusercontent.com/assets/6106623/12687733/4c1d179e-c697-11e5-8a7c-6f1d56dfbdc6.png)

I verified that when I went back to 2.2.6, the behavior went away.  Then I verified that this only happens if you have org.gradle.daemon=true.  I didn't go back far enough yet to figure out when this exactly started happening yet.

**Comment by Jolter** [comment]
Seeing the same here. Quite annoying. Also on 3.4.0.

**Comment by jfbibeau** [comment]
Seeing the same thing here, super annoying as I can't run my "clean" tasks anymore... Any chance for a fix?

**Comment by Jolter** [comment]
Error persists in 3.5.0 according to my tests, so maybe the milestone should be changed?

**Comment by DanielThomas** [comment]
Yeah, that milestone should have been renamed when we needed to push out a minor release. It's now 3.6.0.

**Comment by sghill** [comment]
This sounds related to #204, which was in today's release of v4.2.0. Could someone check if it is now fixed? 

cc: @Jolter @jfbibeau @novasbc

**Comment by jfbibeau** [comment]
Great, I'll take a look at it tomorrow and see if it's fixed!

**Comment by jfbibeau** [comment]
After updating to plugin version 4.2.0, the problem does indeed seem to have gone away!

(fyi - I'm using Gradle 2.11. Is plugin version 4.x.x supposed to work with Gradle 2.x? The changelog seem to imply that it only works with Gradle 3.x but the wording is unclear)

**Comment by sghill** [comment]
Thanks for confirming!

Officially, plugin version 4.x only supports gradle 3.x. In practice the docker integration is currently the only thing no longer works in 2.x.
