### ISSUE TITLE
Is it possible to generate a spec file from RPMs built with nebula?

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#154]
I am in the process of converting a large system based on rpmbuild and spec files to use gradle and the nebula plugin.  It would be helpful to me to be able to see a "spec file" that is equivalent to the spec file used with rpmbuild, for comparison purposes.  I know that this plugin is NOT a wrapper around rpmbuild like the rpm-maven-plugin, but this would still be useful.

In lieu of that, I'd be interested in hearing of other methods people have for comparing an rpm built the old way with an rpm built with this plugin.

**Comment by bmoyles** [comment]
You may want to look at something like http://rpmrebuild.sourceforge.net/ which will give you an approximation of a spec file from a binary RPM. Binary RPMs, unfortunately, don't package the spec files. That, of course, wouldn't include any special logic in a spec file that led to a particular RPM, but may provide something useful for comparison.

**Comment by sc1478** [comment]
Thanks!
