### ISSUE TITLE
The instructions for applying nebula rpm don't work

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#155]
There is a problem with the old plugin syntax instructions for nebula rpm on [(https://plugins.gradle.org/plugin/nebula.rpm)] 

The instructions under 

> "Build script snippet for new, incubating, plugin mechanism introduced in Gradle 2.1:"

 do work.

But I want to do this at the parent level and they fail because of the "Can only be used in build scripts" restriction described on this page.

So I thought I would try to use the older syntax under 

> "Build script snippet for use in all Gradle versions:"

, even though I am using Gradle 2.10.

This does not work:

> * What went wrong:
> A problem occurred evaluating script.
> > Plugin with id 'nebula.rpm' not found.
> 

I also tried switching the repository to jcenter() with the same results.  How can I make this work?

**Comment by DanielThomas** [comment]
@sc1478 looks okay here - that snippet is doing exactly the same thing as the `plugins` block does behind the scenes. Are you still having this problem?

**Comment by sc1478** [comment]
So much water has gone under the bridge since I wrote this that I can scarcely remember the issue at all.  At any case, I am now using the "new" syntax in the build script for a plugin that I have written, which depends on your plugin.  And also using gradle 2.11.  Somehow with all this, I no longer have any problems.
