### ISSUE TITLE
Failing tests 

### ISSUE THREAD

**Issue by dparasam** [nebula-plugins/gradle-ospackage-plugin#158]
I am building from the master and getting these test failures.  Any thoughts on how to fix it?

:test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

com.netflix.gradle.plugins.deb.DebPluginTest > Does not throw UnsupportedOperationException when copying external artifact with createDirectoryEntry option    FAILED
    java.lang.VerifyError at DebPluginTest.groovy:686

com.netflix.gradle.plugins.rpm.RpmPluginTest > Does not throw UnsupportedOperationException when copying external artifact with createDirectoryEntry option    FAILED
    java.lang.VerifyError at RpmPluginTest.groovy:1006

134 tests completed, 2 failed, 3 skipped
:test FAILED

**Comment by DanielThomas** [comment]
I'd need to see the stacktrace to be sure, but there were compatibility issues with early version of JDK 8. Try upgrading.

**Comment by dparasam** [comment]
Thanks.  I tried with Java 8u73 and it works (earlier I had Java 8u20)
