### ISSUE TITLE
rpm fails to install with error "headerRead failed: Header sanity check: OK"

### ISSUE THREAD

**Issue by dparasam** [nebula-plugins/gradle-ospackage-plugin#162]
$ rpm -Uvh SomePackage-201603041411.x86_64.rpm
error: SomePackage-201603041411.x86_64.rpm: headerRead failed: Header sanity check: OK
Segmentation fault
$ rpm --version
RPM version 4.4.2.3
$ cat /etc/redhat-release
CentOS release 5.10 (Final)

The same package works fine on CentOS 7.0.1406 running rpm 4.11.1

**Comment by mbrouer** [comment]
I have the same problem. Guess it time to re-install the old Centos 5 box

**Comment by clintongormley** [comment]
Getting the same thing on SLES 11 SP4

**Comment by clintongormley** [comment]
Looks like it is an issue in redline: https://github.com/craigwblake/redline/issues/97

**Comment by carlolf** [comment]
Any news on this issue?

**Comment by DanielThomas** [comment]
It's not fixed in the upstream project, so we're not able to do anything about it I'm afraid. Additionally, we don't use RPMs here, so while we're happy to accept pull requests and keep the lights on for RPMs, we typically won't chase down issues like this. We depend on the community for that.

**Comment by DanielThomas** [comment]
@niwek still not fixed in redline unfortunately. Not aware of a workaround, but hopefully someone else here can suggest a workaround.

**Comment by lakshgupta** [comment]
The version 3.2.1 of the plugin seems to be working fine. But when I switched to 4.0.0 I started observing this error.

OS: SLES 11 Patch 1 
RPM version : 4.4.2.3

**Comment by sghill** [comment]
It may be worth trying again to see if this is fixed in the most recent version of ospackage.

https://github.com/craigwblake/redline/pull/104 was merged a few months back and released as redline-1.2.3. Our ospackage v4.2.0 release was the first version to include this upstream change.

**Comment by pradeepbansal00** [comment]
Is this issue intermittent or always happen, i build rpm with  version v4.0.0 and it got installed successfully on RPM version 4.4.2.3
