### ISSUE TITLE
Can we get support for changelogs?

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#164]
The Maven RPM plugin has an option for inserting (somehow) a changelog into an RPM.  This would be nice to have in the nebula plugin as well, although I'm guessing that this would also require enhancement of the Redline library.

**Comment by sc1478** [comment]
I notice an issue (#109) concerning Debian packages, but don't know how to insert changelogs into rpms.  I understand that they are not required, but I am replacing a system that uses them and the rpm executable offers an option that shows changelogs if they are there and I'd like to have this available.

**Comment by rspieldenner** [comment]
We don't use changelogs internally for our debians/rpm internally. We're open to a pull request.

**Comment by sc1478** [comment]
Unfortunately, I know nothing of how they are internally implemented.  Do you think it would also require Redline RPM changes?

**Comment by bmoyles** [comment]
If I'm not mistaken, changelogs in RPM files are just headers. You'd need to maintain the changelog externally and read it in at build time, adding the appropriate headers.
Redline provides an enum that references the changelog header fields
http://redline-rpm.org/apidocs/org/redline_rpm/header/Header.HeaderTag.html
but the top-level builder doesn't appear to provide methods specific to changelogs so one would likely need to use addHeaderEntry() with the appropriate header tags from that enum for every changelog entry.

**Comment by sc1478** [comment]
Thanks, Brian!

**Comment by sc1478** [comment]
Hmm, I wonder what all those different changeLoggy things mean!  they're not documented even in the Redline Source.  I see 
CHANGELOG 
CHANGELOGNAME 
CHANGELOGTEXT 
CHANGELOGTIME 

I don't know how (or if) these fit together.  I wonder if CHANGELOG could represent the entire text of a bunch of ChangeLog entries whereas the other three might be tags for adding fields of a specific entry.  If that is the case, then I don't see how CHANGELOG fits together with the other three.  

If CHANGELOG is, as I surmised above, a tag for entering an entire changelog (presumably formatted correctly or it blows up somewhere down the line) then it would be similar to the Maven plugin except that the Maven plugin works by writing a script file and throwing it at rpmbuild.  If it means something else, then this would get much harder.  Is there any way to get an answer to this?  Are you folks in touch with the Redline folks?

**Comment by bmoyles** [comment]
I am not personally involved with the Redline guys (we started this when we were straddling a RPM/Deb world and are now pure Deb, so we don't touch that side much these days).

Near as I can tell from reading over 
http://rpm5.org/docs/api/pkgformat.html
and
http://rpm5.org/docs/api/rpmlib_8h.html (which looks to be where the Redline header tags come from)

as well as looking at /usr/include/rpm/rpmlib.h directly, CHANGELOG appears to refer to an array of CHANGELOG items which are composed of CHANGELOGTIME, CHANGELOGNAME, and CHANGELOGTEXT and neatly maps to the %changelog section of a spec file (described here http://www.tldp.org/HOWTO/RPM-HOWTO/build.html )

What's unfortunate (at least after skimming the source) is that it doesn't appear that Redline supports adding arbitrary headers with array values, only simple string values
https://github.com/craigwblake/redline/blob/master/src/main/java/org/redline_rpm/Builder.java
so I don't know that this would be possible without enhancements to Redline as well.

**Comment by sc1478** [comment]
Thanks again, Brian.  Going to have to study this carefully.  Not sure which way I want to go with this.  It's possible we don't even need changelogs that much, since they aren't required to do the build.  If I do, what is the procedure?  Do I do the pull request first or only when I want to check in code?

**Comment by bmoyles** [comment]
I'd submit the PR once you've worked up the necessary changes and feel it's ready for testing and review. I typically fork a project into my personal account, make changes in a branch there, and then issue the PR from the branch in my fork once it feels "done"

**Comment by sc1478** [comment]
Well, I gave it my best shot and I'm about to give up, I think.

My first effort was done in nebula.  I wrote a change log parser, that was the easy part. 

Second of all, I realized that the changes had to be made in Redline, they are far too low-level to handled by nebula.  But that was okay, Redline is open-source too. So I forked a copy of that and began playing with it.  I ported my parsing logic to that project.  That would have only required a minor change to nebula (to use a different version of redline (my private one) and add a method for adding the changelog file.

I dug through that and through the mindboggling complications of dealing with generic arrays in java and figured out how to add the headers, adding the missing methods you noticed in redline.  When I finally got the whole mess to build without error, it worked.  Except my sample changelog file had two entries.  Only the second one showed up!

After scratching my head on that one, I came upon [this redline source](https://github.com/craigwblake/redline/blob/master/src/main/java/org/redline_rpm/header/AbstractHeader.java), line 47:

	protected final Map< Integer, Entry< ?>> entries = new TreeMap< Integer, Entry< ?>>();

which told me that, Doh!, the entry collection was a Map and each entry put there would overwrite the previous one of the same tag, which completely accounted for the symptoms.  Change log entry tags are quite clearly NOT unique in a changelog.  

So I added a separate list for them in the header class, figured out how to get redline to accept it and write it all out to disk without blowing up due to ClassCastExceptions, fired it up, and lo and behold, it's STILL only showing me the second of my two entries.  Clearly these things are being wrapped in some sort of container when rpmbuild builds the rpm but I'll be damned if I can figure out what that is from the source.  And that's enough for now.

**Comment by sc1478** [comment]
Solved it!  The key was studying the source code for rpmbuild, from the source rpm and not trying to read it on the web.  I had to dig into what `headerAddOrAppendEntry()` was actually doing, as in  [source code](http://rpm5.org/docs/api/parseChangelog_8c-source.html).  There was no functionality in redline to do anything like this, so I added it and it works.  This is cool, it now offers the chance of building rpms on any system, not just systems where rpmbuild is installed, with changelogs.

Now comes the hard part - getting corporate to agree to allow me to contribute this back.  It's supposed to be easier than it was before, but I'm a bit apprehensive about the sketchy [Redline FreeCompany license](https://github.com/craigwblake/redline/blob/master/license.txt).  It's not on the approved list as this project's Apache license is.

**Comment by sc1478** [comment]
I've submitted a Pull Request to Redline RPM for Changelog.  https://github.com/craigwblake/redline/pull/105. If they accept it, I'll soon have another one here to use it.

**Comment by sc1478** [comment]
Pull Request submitted: https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/205

**Comment by sghill** [comment]
#205 released today as v4.2.0
