### ISSUE TITLE
FR: Please allow provide directory owner

### ISSUE THREAD

**Issue by Hubbitus** [nebula-plugins/gradle-ospackage-plugin#165]
https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/master/Plugin-Rpm.md#directories describe how to provide permissions. It seams impossible provide different owner than default.

**Comment by jfbibeau** [comment]
Hitting the same problem. It looks like by default the directory is created with the same user as the `packager` attribute of the rpm task with no way to change it.

**Comment by sghill** [comment]
This sounds related to #207, which was released in v4.3.0. Could you confirm?
