### ISSUE TITLE
Error building the plugins

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#167]
I am trying to build a forked version of the plugin.  I've never built the plugin before, forked or unforked, but I doubt that anything I have done could have caused this:

```
~/gradle-ospackage-plugin (master)$ ./gradlew publishNebulaPublicationToMavenLocal

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sc1478/gradle-ospackage-plugin/build.gradle' line: 27

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.nebula-release', version: '3.1.2']
> Failed to apply plugin [id 'nebula.nebula-release']
   > The nebula-release-plugin requires a Git tag to indicate initial version. Use "git tag v1.0.0" to start from version 1.0.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.851 secs
```

I am not sure what to do here.  I've run git tag and see that it's made tags in the appropriate place, but I still get the error.  How do I get beyond this?

**Comment by sc1478** [comment]
Ok, solved it myself.  The issue for me was that the [root of my git installation was not the same as that of my gradle installation.](https://github.com/nebula-plugins/nebula-release-plugin/blob/master/README.md#git-root-is-in-a-different-location-from-gradle-root)

**Comment by sc1478** [comment]
Okay, as indicated in previous comment, this got me off the dime:

`./gradlew -Pgit.root=`which git` clean publishNebulaPublicationToMavenLocal`

However, it still put a version number of 'unspecified' on the archive deployed into the local Maven repository.

I worked around this by supplying a version property in my build script for gradle-ospackage-plugin, which is something that the original did not have.  How is this supposed to work?

**Comment by sc1478** [comment]
odd:

```
~/gradle-ospackage-plugin (master)$ which git
/usr/bin/git
```
But 
```
./gradlew -Pgit.root=`which git` clean publishNebulaPublicationToMavenLocal
```
gives me a version of unspecified in the repo while 
```
./gradlew -Pgit.root=/usr/bin/git clean publishNebulaPublicationToMavenLocal
```
gives me the correct version number in the repo.

**Comment by nadavc** [comment]
The original error you saw actually came from nebula-release-plugin, which is the plugin we use to version and release modules. The nebula-release-plugin uses Git tags to keep track of versions, and and it was asking you to provide an initial tag to start versioning from. The same plugin also assumes that the `.git` directory will be present in the same directory as the root Gradle project. If that assumption is incorrect, you can specify the right location for `.git` using the `git.root` parameter ([docs](https://github.com/nebula-plugins/gradle-ospackage-plugin.git)). Note that this isn't for the location of the git binaries themselves.  

I believe you should be able to get the result you're looking for by doing a fresh clone and running `./gradlew build publishToMavenLocal`. Please feel free to reopen if you run into problems.

**Comment by vmahuvak** [comment]
I have set git.root=-P<path .git for may project> as it is in a directory higher level than my gradle project. It works file when I run on my Mac

gradle final -Dorg.ajoberstar.grgit.auth.username=<USERNAME> -Dorg.ajoberstar.grgit.auth.password=<PASSWORD> -Pgit.root=/Users/vikrammahuvakar/projects/mytest final 

but it fails on Cloudbuild  as I cannot set -Pgit.root=<..>
I tried 
-Pgit.root=$REPO_NAME 
-Pgit.root=/workspace

Any suggestion how I can set this for Cloudbuild in my cloudbuild.yaml file??
