### ISSUE TITLE
Misleading documentation of requires method

### ISSUE THREAD

**Issue by wallner** [nebula-plugins/gradle-ospackage-plugin#169]
The documentation of the [requires method](https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/master/Plugin-Deb.md#requires) is misleading, it states that

> Required packages are specified via the required method:
>   `requires(String packageName, String version)`

However, this method does not exist in `SystemPackagingExtension.groovy` and when I try to specify  a version for a dependency like this:

```
requires('firefox', '45.0')
```

The build fails with 
```
Could not find method requires() for arguments [firefox, 45.0] on root project ...
```

**Comment by nadavc** [comment]
Thanks for reporting the issue. I've updated the docs to reflect the current state. Please let us know if you find any other problems.
