### ISSUE TITLE
Build script hacks make pull requests difficult

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#178]
This is my "answer" to [Issue 176.](https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/176).  Basically, I've given up on getting the tests to work given the changed circumstances of my build.

The basic problem is that my fork, and hopefully a later pull request [for issue 164](https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/164), is mainly to incorporate a change I had to make to Redline, and then a little glue code to get it to work in a new version of os-nebula plugin.  My stuff all works but it breaks your unit tests, due to classpath issues.  I simply can't figure out a way to get my redline from a different repository (my local one) while the rest of the dependenicies come from jcenter, without breaking your tests.  Compiling the main code and the test code works fine but there are ClassNotFoundErrors when **running** the tests - more precisely, when **the tests launch a build script that uses the plugin, using yet another classpath**.

It's all too much for me to figure out with my less than expert knowledge of gradle, and the code in your build script is a bit ragged, sorry to say.  I refer specifically to [build.gradle](https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/master/build.gradle) line 54: 

`apply from: 'https://raw.githubusercontent.com/nebula-plugins/nebula-core/b676bbc026d0053494b5439ba8ef147c16adabba/common.gradle'`

which in turn "includes" ['https://raw.githubusercontent.com/nebula-plugins/nebula-core/b676bbc026d0053494b5439ba8ef147c16adabba/common.gradle':](url), including new `repositories{}` and `dependencies{}` closures whose effect, in conjunction with the rest of the build script code, I can't really understand.

My worakaround plan is just to turn off the tests while I wait for company approval to submit my redline changes and for redline to accept them.  Once all that happens, my changes to your build script would require only a simple version bump for redline.

However, it would be nice if someone could make your build script less brittle and more standard.  It would make submitting pull requests easier.

**Comment by sghill** [comment]
Closing as the referenced issues (#164, #176) are now closed and the build file no longer applies from a url.
