### ISSUE TITLE
Request to expose vcs property

### ISSUE THREAD

**Issue by dhyaneshm** [nebula-plugins/gradle-ospackage-plugin#181]
Can someone expose vcs property for rpm
Error that i get :

`> No such property: vcs for class: com.netflix.gradle.plugins.packaging.ProjectPackagingExtension_Decorated
  Possible solutions: os, arch, url, gid, uid
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.`

**Comment by sghill** [comment]
Would you be interested in submitting a pull request for this feature?
