### ISSUE TITLE
Question about linking multiple files

### ISSUE THREAD

**Issue by colindean** [nebula-plugins/gradle-ospackage-plugin#185]
I have a task that produces manpages. There is one now, but there will be a lot more in the future, so I'd like to programmatically link them instead of listing them one by one.

I tried this inside my `ospackage` task:

```gradle
ospackage {
<stuff>
def manpages = fileTree(dir: "${buildDir}/dist/share/man", include: '*.\\d')
  manpages.visit { manpage ->
    def number = manpage.getName.split('.')[1]
    link("/usr/local/man/man${number}/${manpage.getName}", "${installDir}/share/man/${manpage.getName}")
  }
}
}
```

This fails to link anything, likely because when `manpages` is defined during Gradle's configuration stage, the manpages do not yet exist! I tried putting the above into a `doLast`, but apparently there is no `doLast` available within the `ospackage` task.

How can I tell Gradle to wait until runtime to lookup what's in that `man` directory?

One way I can think is to use the output of the manpage generation tasks. However, the task that writes the file doesn't declare outputs (I couldn't figure out how to do that?). That task is also specific to one file and doesn't account for multiple output files just quite yet.

This is probably more of a Gradle usage question than `ospackage`-specific...

**Comment by rspieldenner** [comment]
ospackage by default creates task buildDeb and buildRpm so you can probably
do a doFirst on one of those to configure the ospackage block after the man
pages are generated

**Comment by nadavc** [comment]
So in other words, the `ospackage` extension object is available to all tasks as well, and you should be able to modify it after the man creation task is done. In this case, you'd probably want to call `ospackage.link()` from your generation task's `doLast()`. Closing this issue as it is not `ospackage` specific...

**Comment by colindean** [comment]
Thanks, @nadavc: your suggestion helped me figure out the solution!
