### ISSUE TITLE
Deb Plugin wiki page should say that packageDescription defaults to project.description

### ISSUE THREAD

**Issue by Thunderforge** [nebula-plugins/gradle-ospackage-plugin#191]
At [SystemPackagingTask.groovy line 83](https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/179e915896951f8ffdfe6a9e641abd6c3828ef8b/src/main/groovy/com/netflix/gradle/plugins/packaging/SystemPackagingTask.groovy#L83), the `packageDescription` property defaults to `project.description` if not explicitly defined. This should be reflected on the [Deb Plugin wiki page](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin). Currently there are no notes about the default values for `packageDescription`.

**Comment by DanielThomas** [comment]
Updated.

**Comment by Thunderforge** [comment]
Thanks for doing this and I appreciate the new table format!

I just noticed that the RPM page is also missing this. Should I create a new issue?
