### ISSUE TITLE
Several issues with rpm and ospackage-application-daemon

### ISSUE THREAD

**Issue by samuelrivas** [nebula-plugins/gradle-ospackage-plugin#194]
Hi,

I _think_ I have found several issues with the RPM packages generated using the ospackage-application-daemon plugin (some of those issues may not be specific to rpms, but I haven't investigated that). In general they are not terrible as they affect mostly the uninstall process.

This is the script I am using. Server.scala is just [Finagle's server example](https://github.com/twitter/finagle/blob/develop/doc/src/sphinx/code/quickstart/Server.scala)

```
buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
        jcenter()
    }

    dependencies {
        classpath "gradle.plugin.com.netflix.nebula:gradle-ospackage-plugin:3.6.1"
    }
}

apply plugin: 'scala'
apply plugin: 'nebula.ospackage-application-daemon'

mainClassName = 'Server'

applicationdaemon {
  user = "some_user"
  autoStart = true
}

task wrapper(type: Wrapper) {
  gradleVersion = '2.14.1'
}
```
### Race condition when creating the daemontools service

The directory `/service/<project>` is part of the RPM structure. Once that is written, `svscan` will find it within 5 seconds and start the server unless `/service/<project>/down` exists. The problem is that `down` is created in the post install phase, so there is a slight chance of the server being started as part of the installation:

```
postinstall scriptlet (using /bin/sh):
 RPM_ARCH=noarch 
 RPM_OS=unknown 
 RPM_PACKAGE_NAME=<project> 
 RPM_PACKAGE_VERSION=unspecified 
 RPM_PACKAGE_RELEASE= 

[ -x /bin/touch ] && touch=/bin/touch || touch=/usr/bin/touch
$touch /service/<project>/down
/sbin/chkconfig <project> on
```

This can be fixed by creating the down file in the pre-install, but as I'll explain below, I don't think the `/service/<project>` structure should be part of the rpm filesystem
### Incorrect generation of `/rcN` scripts

The `/etc/rcN` scripts are generated with `/sbin/chkconfig <project> on` (see snipped above). I think what you want to do is actually `/sbin/chkconfig --add <project>`. The former will create S scripts in runlevels 2, 3, 4, and 5, whereas the latter will create all S and K scripts according to the configuration written down in `/etc/init.d/<project>` (which I understad acknowledges the `server.runLevels` property)

Also, there is no cleanup for this in the uninstall. `/sbin/chkconfig --del <project>` should be called in either pre or post uninstall
### `/service` is part of the RPM filesystem

The proper way of installing a server with daemon tools is to symlink its server descrption to `/service/<project>.` The reason for that is that symlinking is an atomic operation so you don't have the problem of `svscan` finding a partly written server, and you can uninstall as suggested in the daemontools guide:

```
cd /service/telnetd
     rm /service/telnetd
     svc -dx . log
```

The way the server is installed now makes it impossible to uninstall properly, or at least I couldn't find a way. What we are doing right now is stopping the service and the log with `svc -d`  in the preuninstall and removing the `/service/<project>` directory in the post uninstall. This still has the problem that the supervise processes are left behind, as it is not possible to stop them in a civilised way once the server directory has been deleted.

I think that, instead, the server data should be written somewhere else (e.g. `/opt/<project>/service`) and symlinked in the postinstall script. The down file can be part of the original directory structure or created by a script before the symlink is done.
### The init.d script assumes that daemontools is in the PATH

The "official" way of runing the daemontools commands is to use an absolute path, they are supposed to be installed in `/command/*` (which is unlikely to be in root's PATH)

By default, the daemontools installation process also writes them to /usr/local/bin, which in some Linuxes is in normal users' path, but it doesn't seem to be in root's path for the distribution I am working with.

Anyway, in my opinion is a safer bet to follow daemontools prescription and use absolute paths in `/command`
### Incomplete cleanup

I already mention some of those, but for completeness. The plugin does very little to make sure all files related to the service are cleaned up. At least I found that it doesn't delete the rcN scripts or the `/service` directory
### No user creation

This is not as much an (alleged) error as a missing feature, but even though one can specify which user should run the daemon, the specified user is not created. This means that all the packages should include creation and deletion rules for the user they specify, which is quite error prone. Since nebula already knows that the user is needed it could include the correct install and uninstall scripts for it.

**Comment by rspieldenner** [comment]
Cleanup on uninstall, we're open to pull-requests. We use immutable infrastructure and don't uninstall rpms/debs ever, just create a new AMI with the new rpm/deb.
