### ISSUE TITLE
how to actually run a `build` or `configure` command

### ISSUE THREAD

**Issue by cdaringe** [nebula-plugins/gradle-ospackage-plugin#195]
hello

per the rpm docs, there should be stanzas in a spec file as such:

```
%build
%configure
make %{?_smp_mflags}
```

however, i'm not sure the parallel stanza used to perform the above in this package.  thanks!

**Comment by cdaringe** [comment]
also, is there a way i can sneak-peek at the generated spec file?

**Comment by rspieldenner** [comment]
We use the redline java library to generate rpms. To the best of my knowledge it doesn't create spec files.
