### ISSUE TITLE
Regression of RPM directory management

### ISSUE THREAD

**Issue by unomar** [nebula-plugins/gradle-ospackage-plugin#197]
It appears that a commit between 3.1.0 and 3.2.0 broke the ability to use the workaround specified in issue #59.  The test specified in [this comment](https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/59#issuecomment-128718128) no longer works after gradle-ospackage-plugin version 3.2.0.

**Comment by unomar** [comment]
Output from 3.1.0
`rpm -qlp build/distributions/foo-1.0.0.noarch.rpm                                                                                                                                                              
/opt/test/foo
...`
Output from 3.2.0
`rpm -qlp build/distributions/foo-1.0.0.noarch.rpm
/opt/test
/opt/test/foo
...`

**Comment by jfbibeau** [comment]
I'm seeing the same thing with 3.4.0. Looks like addParentDirs doesn't have any effect anymore.

**Comment by jfbibeau** [comment]
Note that if you move addParentDirs out of the from closure and into the task itself, it actually works and correctly removes all directories from being managed by the rpm. But then you have to re-add every subdirectory you actually do care about.

**Comment by grkg8tr** [comment]
I'm having this same issue in 4.1.0. But don't really want to make it global to the task. Is this something that can be fixed?

**Comment by grkg8tr** [comment]
I found this behavior in 4.1.0 to change based on if I'm using `addParentDirs false` and `addParentDirs = false`. The first doesn't work, but the later does. The `Plugin-Rpm.md` file states that both methods should be supported, but I'm only having success with the assignment. I'm not sure why this would be handled differently, but hopefully it gives another clue.

**Comment by grkg8tr** [comment]
I think this is related to #124 and #212. I've added a [pull request](https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/197) to fix the issue.

**Comment by sghill** [comment]
Fixed with the release of v4.3.0 today

**Comment by jonpeterson** [comment]
I don't think this is fixed entirely: #246
