### ISSUE TITLE
DEB: Cannot set arch = armhf

### ISSUE THREAD

**Issue by CraziFuzzy** [nebula-plugins/gradle-ospackage-plugin#198]
Trying to port a project to run on Raspberry Pi, which is the armhf architecture, but I cannot set the arch to that in my build.  I can only set it to arm, which then fails out installing with dpkg unless i add a foreign arch, or force it to ignore architecture.

**Comment by rspieldenner** [comment]
We just pass the archStr through to jdeb.

What kind of error are you seeing when you set arch to `armhf`

**Comment by CraziFuzzy** [comment]
I am getting:
`A problem occurred evaluating root project 'opendct'.
> Could not find property 'ARMHF' on task ':packageDebArm'.`

**Comment by rspieldenner** [comment]
Could you post as much as the build.gradle file as you feel comfortable
doing? At minimum the debArm/packageDebArm task, ospackage or deb
configuration

**Comment by CraziFuzzy** [comment]
it's open source, so it's here:
https://github.com/CraziFuzzy/opendct/blob/master/build.gradle

**Comment by CraziFuzzy** [comment]
Any thougts on this?  Primarily want to make sure I'm not doing something wrong here.

**Comment by sghill** [comment]
Try as a string `'ARMHF'`. That works for me locally.

v2.2.2 (specifically https://github.com/nebula-plugins/gradle-ospackage-plugin/commit/20fd9f35b6a892b70914dba9818adcd5fd1f749c) started allowing strings to handle architectures not present in the Redline Architecture enum.
