### ISSUE TITLE
Push RPM to remote repository

### ISSUE THREAD

**Issue by markandirene** [nebula-plugins/gradle-ospackage-plugin#199]
Hello

Is there an easy way to push the generated RPM to a remote Nexus repository?

Thanks

Mark

**Comment by rspieldenner** [comment]
This plugin is intended to create RPMs and DEBs. I would keep a separation
of concerns around publishing. We have an internal plugin for publishing to
our Artifactory repository.

We don't use Nexus internally so wouldn't spend the resources to create a
Nexus publishing plugin. If you would like to create one and would like it
hosted under the Nebula name, we can create a repository.
