### ISSUE TITLE
Rpm Task is not properly closing file!

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#200]
For awhile now, I've been noticing that when building RPMs under Windows using your plugin, the plugin was not properly closing the rpm file it built.  If running Gradle from Eclipse, I could not make an RPM and then run the clean task on the same gradle project without restarting Eclipse.  Nor could I open the rpm to have a look with something like 7-Zip.  I then realized it had nothing to do with Eclipse - running from a command line under windows with the Gradle Daemon running, I could not clean the project after having built the rpm.  In that case, you could work around the problem by not using the daemon.  In the former case Eclipse owns the file handle, in the latter case, the daemon owns it.

For awhile I assumed the problem was something I was doing in my own plugins which extend your Rpm plugin.  But this afternoon I tried removing that questionable code and the problem persisted.  I then had a look at Redline's code - and the nebula.rpm's.  

The bug is in the nebula.rpm plugin.

First, here is the Redline code (with a few comments made by me.

```
    /**
     * Generates an RPM with a standard name consisting of the RPM package name, version, release,
     * and type in the given directory.
     *
     * @param directory the destination directory for the new RPM file.
     * @return the name of the rpm
     * @throws NoSuchAlgorithmException the algorithm isn't supported
     * @throws IOException there was an IO error
     */
    public String build( final File directory) throws NoSuchAlgorithmException, IOException {
        final String rpm = format.getLead().getName() + "." + format.getLead().getArch().toString().toLowerCase() + ".rpm";
        final File file = new File( directory, rpm);
        if ( file.exists()) file.delete();
        RandomAccessFile raFile = new RandomAccessFile( file, "rw");
        build(raFile.getChannel());
        raFile.close();  // NOTE: this is the only place that closes the file.
        return rpm;
    }

    /**
     * Generates the rpm file to the provided file channel. This file channel must support memory mapping
     * and therefore should be created from a {@link RandomAccessFile}, otherwise an {@link IOException} will be
     * generated.
     *
     * @param original the {@link FileChannel} to which the resulting RPM will be written.
     * @throws NoSuchAlgorithmException the algorithm isn't supported
     * @throws IOException there was an IO error
     */
    @SuppressWarnings( "unchecked")
    public void build( final FileChannel original) throws NoSuchAlgorithmException, IOException {
             .. a lot of low level code which IMPORTANTLY DOES NOT CLOSE the FileChannel
    }
```

Now, here's the plugin code from RpmCopyAction.groovy.  This is where the redline builder is invoked to actually build the rpm file:

```
    @Override
    protected void end() {
        File rpmFile = task.getArchivePath()
        FileChannel fc = new RandomAccessFile( rpmFile, "rw").getChannel()
        builder.build(fc)
        logger.info 'Created rpm {}', rpmFile
    }
```

Note that the plugin is calling the `builder.build(FileChannel)` method which doesn't close anything, not the `builder.build(File)` method, which would actually close the file .  This is why the file is remaining open.  
Recoding this method to this:

```
    @Override
    protected void end() {
        File rpmFile = task.getArchivePath()
        builder.build(task.getDestinationDir())
        logger.info 'Created rpm {}', rpmFile
    }
```

solves the problem!

The plugin needs to close the file.  I'm not sure why the `build(FileChannel)` method isn't private, but if you call it, you're responsible for closing the file.

I suppose this would also work:

```
    @Override
    protected void end() {
        File rpmFile = task.getArchivePath()
        FileChannel fc = new RandomAccessFile( rpmFile, "rw").getChannel()
        builder.build(fc)
        rpmFile.close()
        logger.info 'Created rpm {}', rpmFile
    }
```

For some reason, this doesn't matter under unix, only under Windows.

**Comment by sc1478** [comment]
Note.  I am using a local modified version based on 3.4.0.  I know you've moved beyond that version, but I can't switch because I've forked redline-rpm and the guy who runs it hasn't moved my Pull Request in almost four months.  But I've checked your latest source code and it still has the same problem as that identified above.

**Comment by carlolf** [comment]
` raFile.close();  // NOTE: this is the only place that closes the file.`

should of course placed into a finally block :-1: )

**Comment by sc1478** [comment]
That is true, but Redline's doesn't either.  This would suggest that my second fix, with the finally block is the right way to go.  I will open a pull request.

**Comment by lkoe** [comment]
Is a release planned, which will contain this fix?

**Comment by sc1478** [comment]
Yes, I would like to know that too.  I am the author of the pull request but not a member of the team that plans releases.

**Comment by sghill** [comment]
@lkoe @carlolf v4.2.0 includes @sc1478's pull request and was released today.

**Comment by lkoe** [comment]
Thanks @sc1478 and @sghill, confirmed working with 4.2.0.
