### ISSUE TITLE
Create multiple debian packages from one source directory?

### ISSUE THREAD

**Issue by bedge** [nebula-plugins/gradle-ospackage-plugin#209]
Is there any provision for creating multiple .deb files packages from one source tree?

I have a single source dir from which I need to build 2 packages as they have different deployment requirements. 

I know I could restructure into multiple gradle projects, but that incurs much more gradle boilerplate overhead.

**Comment by DanielThomas** [comment]
You can avoid boilerplate by using a subprojects block in a parent project, or an apply from a common file that gives you conventions for your packages. You can create deb tasks yourself, but it'd be more boilerplate and more opportunity for complications.
