### ISSUE TITLE
Use ospackage rpm in a groovy plugin

### ISSUE THREAD

**Issue by damsazio** [nebula-plugins/gradle-ospackage-plugin#210]
Hi everybody,
I'm trying to use ospackage to create a rpm but instead of using it like in the wiki example (directly as a gradle task), I have to use it in a GroovyPlugin.
When I fill all the required attributes like packageName, version, ... I got the following error:

> What went wrong:
> Execution failed for task ':Modeles:creerRpm'.
> Invalid package name 'null' - a valid package name must only contain [a-zA-Z0-9-._+]

I know that my task (creerRpm) is known as a task that have to create rpm because I have the error (so ospackage is ok) but I don't know why the attributes aren't recognized as they have to.

My build.gradle:

```
apply plugin: 'groovy'
apply plugin: 'eclipse'
apply plugin: 'idea'

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    compile gradleApi()
//  compile localGroovy()
    compile 'org.yaml:snakeyaml:1.14'
    compile 'org.codehaus.groovy:groovy-all:2.4.4'
    testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
    testCompile 'org.xmlunit:xmlunit-core:2.2.0'
    // L'utilisation du mock dans les test dépend de cglib (sans dépendannce)
    testCompile "cglib:cglib-nodep:2.2"
    compile 'com.netflix.nebula:gradle-ospackage-plugin:2.2.6'
}

```

My file ModelesPlugin.groovy (the rpm creator):

```
import com.netflix.gradle.plugins.rpm.Rpm
import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project

class ModelesPlugin implements Plugin<Project> {

void apply(Project project) {
    project.task('creerRpm', type: Rpm) << {
        creerRpm(project)
    }
    void creerRpm(Project project) {
        type SOURCE
        arch = NOARCH
        packageName = "test"
        version =1
        release = 1
        os = LINUX
         project.fileTree(source).findAll{
             it.name.startsWith("IC-")
         }.each{ fichier ->
             from(fichier.absolutePath) {
                 into '/var/toto'
             }
         }
    }
}
```

I tried to put the code of creerRpm directly under the task with no effect. I don't know what I'm doing wrong. Do you have any clue?

Thanks
Damien

**Comment by damsazio** [comment]
Sorry, I forgot to tell that source (in `project.fileTree(source).findAll{`) is Ok too. If I println it.name I got the list of file.
(I paste my code too early :) )

**Comment by sghill** [comment]
v2.2.6 is quite old. v4.3.0 is the current version and contains several RPM-related pull requests from the community. 

Do you get better results with more recent versions of the plugin?

**Comment by damsazio** [comment]
Hi,
I updated to 4.3.0 (was 4.1.0 before reading your answer).

I manage to initialize attributes like type, arch, release, ... using:
`project.tasks.buildRpm.setProperty(release,1)` but had problems with into, from ... the builded rpm was empty...

And the second point is that I was obliged to to programmatically execute buildRpm using `project.tasks.buildRpm.execute()`, that is not a good solution for me.

For the moment I did not manage to use the following declaration:
```
project.task('createRpm', type: Rpm) {
   release 1
   packageName 'myRpmName`
   [...]
}
```
To conclude, the only way to do what I want (building a rpm with different parameters passed in a plugin) is:
 - have a rpm.gradle file in which there is a task buildRpm containing:
```
buildRpm {
    outputs.upToDateWhen {
        if(project.modelesConfiguration.nested.creation_rpm) {
            type = project.modelesConfiguration.nested.type
            packageName = project.modelesConfiguration.nested.packageName
            version = project.modelesConfiguration.nested.version

            project.modelesConfiguration.nested.source.each { fichier ->
                from(fichier.absolutePath) {
                    into project.modelesConfiguration.nested.into }
            }
        }
        return false
    }
}
```
 - then put the value I want to my differents parameters (project.modelesConfiguration.nested.*),
 - finally force the execution of buildRpm task.

**Comment by sghill** [comment]
Thanks for the followup -- glad to see a workable solution was found.
