### ISSUE TITLE
contains illegal character ~ 

### ISSUE THREAD

**Issue by Gehadelrobey** [nebula-plugins/gradle-ospackage-plugin#213]
I get this issue when I build with gradle 3.11 and ospackage-plugin 3.2.0

java.lang.IllegalArgumentException: version with value: '1.1.0~dev.0.uncommitted' contains illegal character ~ at org.redline_rpm.Builder.checkVariableContainsIllegalChars

ospackage-plugin is supposed to sanitize gradle project version and replace "-" with "~", but redline doesn't allow "~" characters in the rpm name

redline version: org.redline-rpm:redline:1.2.1

**Comment by sghill** [comment]
The change allowing `~` in RPM versions and releases was merged into the redline library yesterday. Once there is a new release of redline, we can update and release ospackage so it will stop throwing the IllegalArgumentException.

In the meantime, there were several workarounds mentioned in #49, including for [dynamically generated versions](https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/49#issuecomment-269254776).
