### ISSUE TITLE
wiki: document alternative dependencies

### ISSUE THREAD

**Issue by samrocketman** [nebula-plugins/gradle-ospackage-plugin#214]
Alternative dependencies were introduced in #187.  It took me a while to figure out how to do it and it was by sheer luck that I decided to search issues and pull requests for the keyword `alternative`.  This should be documented in the [Deb Plugin wiki page](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin#requires) preferably under `Requires` section.

**Comment by samrocketman** [comment]
It took me a while to figure out how to use it.  Example,

```
Depends: default-jre-headless (>= 2:1.7) | java7-runtime-headless
```

is equivalent to

```groovy
import org.redline_rpm.header.Flags
...
ospackage { ... }
buildDeb {
    ...
    requires('default-jre-headless', '2:1.7', Flags.GREATER | Flags.EQUAL).or('java7-runtime-headless')
    ...
}
...
```

See also [Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-relationships.html#s-depsyntax).

**Comment by sghill** [comment]
Thanks! Documented [here](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin#alternative-dependencies) now.
