### ISSUE TITLE
Possible to configure Automatic Dependencies ?

### ISSUE THREAD

**Issue by thokari** [nebula-plugins/gradle-ospackage-plugin#215]
There is the setting `AutoReqProv: no` to disable the resolution of automatic dependencies. I see this in a spec file I am trying to refactor to use this plugin. Is there a way to make this setting?
See also http://www.rpm.org/max-rpm/s1-rpm-depend-auto-depend.html

**Comment by sghill** [comment]
[Redline](https://github.com/craigwblake/redline) is the library ospackage uses to create RPMs. I searched for `AutoReqProv` in that repository and didn't find anything. We'd be open to a pull request if it is supported.
