### ISSUE TITLE
Deb maintainer scripts are not added as task inputs

### ISSUE THREAD

**Issue by ngaya-ll** [nebula-plugins/gradle-ospackage-plugin#217]
When configuring maintainer scripts for a Deb task ([docs](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin#scripts)), the specified script files do not seem to be added as task inputs.  This means the task sometimes does not run when it should (i.e. when the specified script files change).

I am using version 3.8.0 of the plugin with Gradle 2.14.1.

**Comment by sghill** [comment]
If you were using this in a custom task of `type: Deb`, the fix for this was released in v4.3.0 today. 

If you're using it in an `ospackage` block, it looks like there is a larger issue with tagging Inputs and convention mappings that will be addressed separately.
