### ISSUE TITLE
Plugin repo issue

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#220]
I'm trying to pull the new version 4.3.0 (same applies to 4.2.0) into my build.

From the [Gradle Plugins page for nebula rpm](https://plugins.gradle.org/plugin/nebula.rpm), I see how I am supposed to use this plugin:

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.netflix.nebula:gradle-ospackage-plugin:4.3.0"
  }
}

apply plugin: "nebula.rpm"
```

but, If I do this in my project and try to build it with --info, I get missing resource errors:

```
Resource missing. [HTTP GET: https://plugins.gradle.org/m2/com/netfix/nebula/gradle-ospackage-plugin/4.3.0/gradle-ospackage-plugin-4.3.0.pom]
Resource missing. [HTTP HEAD: https://plugins.gradle.org/m2/com/netfix/nebula/gradle-ospackage-plugin/4.3.0/gradle-ospackage-plugin-4.3.0.jar]
```

If I put the first of these links into my browser, I get a redirection that shows me a 404. See attached screenshot.
![2016-12-15_10-30-49](https://cloud.githubusercontent.com/assets/15382550/21234464/5a9f78f2-c2b8-11e6-8b6d-92fbfdfba109.png)

Clearly something appears to be wrong in the setup of the repository.
And the same appears to happen with any earlier version of the plugin, 4.2.0, 4.0.0, etc.

**Comment by DanielThomas** [comment]
Note `com/netfix` - believe you had a typo in your original build script.

**Comment by sc1478** [comment]
D'Oh!

Thanks.  Sometimes you get into a mindset.  I couldn't see the error until I put the correct and incorrect urls right next to one another.
