### ISSUE TITLE
Non latin files in rpm

### ISSUE THREAD

**Issue by bvp** [nebula-plugins/gradle-ospackage-plugin#237]
Hello! I have a problem!
```bash
$ sudo rpm -i appserver-4.1712.229-test.noarch.rpm
error: unpacking of archive failed on file ./opt/appserver/lib/js/ui/accounting/???????????? ??????????.docx: cpio: Archive file not in header
error: appserver-0:4.1712.229-test.noarch: install failed
```

in build.gradle
```groovy
buildscript {
    dependencies {
        classpath "com.netflix.nebula:gradle-ospackage-plugin:4.4.0"
    }
}
apply plugin: 'nebula.ospackage-base'
...
task createDistrRpm(type: Rpm, group: "distribution", dependsOn: "createDistr") {
    packageName 'appserver'
    version version
    release branchName
    arch NOARCH
    os LINUX
    requires("jre", "1.6.0", GREATER | EQUAL)

    into '/opt/appserver'
    from destDir
}
```
Original filename have correct encoding (cyrillic)
Trying to creating cpio archive from command line - correct content

**Comment by bvp** [comment]
Maybe problem in https://github.com/craigwblake/redline ?

**Comment by bvp** [comment]
Fixing after update org.redline-rpm:redline to new version. Waiting accepting pull request in redline repo

**Comment by jandrops** [comment]
Hi, 

I got the same issue with a file that contains an accent mark 'é'. 

After creating a RPM using the **gradle-ospackage-plugin**, I try to unpack it using the command:
`rpm2cpio RPMS/*.rpm | cpio -idmv`
and the file called:
`Frédéric.json`
is extracted as:
`Fr?d?ric.json`

Any idea if there is going to be a new version of **org.redline-rpm:redline** soon to get this issue fixed for the **gradle-ospackage-plugin**?

Thanks!

**Comment by bvp** [comment]
@jandrops we use the patched version of redline in the gradle-ospackage-plugin to avoid this

**Comment by jandrops** [comment]
Hi @bvp, so that means that you build the gradle-ospackage-plugin against locally patched redline?

Is there any way to add a dependency in my build.gradle to use gradle-ospackage-plugin containing the redline fix (as the latest version of the gradle-ospackage-plugin is uses redline version 1.2.5)?

**Comment by bvp** [comment]
we use artifactory for this
