### ISSUE TITLE
Support for debconf configuration files

### ISSUE THREAD

**Issue by jonathansloman** [nebula-plugins/gradle-ospackage-plugin#238]
When using debconf, we need some extra files in the debian package maintainers area, specifically 'templates' and 'config'. I can't find any way to get these files in there with the current plugin - only the preinst/postinst etc files seem to be supported. I tried manually copying them into build/debian before running makeDeb, but unfortunately that directory gets wiped out by the makeDeb task.

Is there any workaround I haven't thought of to get this to work, or does the plugin need work to support it?

Thanks,

**Comment by jonathansloman** [comment]
I've submitted a pull request with a fix for this issue.

**Comment by jonathansloman** [comment]
I've just stumbled across the 'supplementaryControl' which negates the need for this. Could this possibly be added to the documentation?!
Thanks..

**Comment by thundertaker** [comment]
Hello, could you please describe? What is the way, for example, of adding debconf templates?

**Comment by jonathansloman** [comment]
Just include lines like this in your makeDeb task:

    supplementaryControl 'src/deb/control/config'
    supplementaryControl 'src/deb/control/templates'

**Comment by thundertaker** [comment]
@jonathansloman thanks, it's working!
