### ISSUE TITLE
RPM Versions are Sanitized with Tilde but Docs Say Not to Use It

### ISSUE THREAD

**Issue by EarthCitizen** [nebula-plugins/gradle-ospackage-plugin#245]
Currently, a version such as `1.0.0-SNAPSHOT` is sanitized to `1.0.0~SNAPSHOT` (replacing dash with tilde).

But according to:

http://fedoraproject.org/wiki/Packaging:Versioning

> The tilde (~) notation which alters the way RPM does version comparisons MUST NOT be used.

**Comment by rpalcolea** [comment]
This opinion has changed -> https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_versioning_prereleases_with_tilde
