### ISSUE TITLE
How to install script as cron job

### ISSUE THREAD

**Issue by DaveBender** [nebula-plugins/gradle-ospackage-plugin#247]
I'm trying to use ospackage to create an rpm that will install a script that will be run by root as a cron job, but I'm not finding examples in the wiki that demonstrate how this is done.  Is this do-able and if so what would be the steps?

**Comment by DanielThomas** [comment]
That's just a matter of dropping a file in `/etc/cron.d`, or proving a script in the package to add the crontab entry. Not a concern of the plugin, which is why we don't document anything like that.
