### ISSUE TITLE
Symbolic links not working

### ISSUE THREAD

**Issue by deepak-shrivastava** [nebula-plugins/gradle-ospackage-plugin#249]
Hi,
I am trying to create a symbolic link. But no matter what i try, i am not able to get the link... I dont get any errors as such but the link is just not present.
here is the snippet of my gradle file
plugins {
  id "nebula.ospackage" version "3.2.0"
}
task fooRpm(type: Rpm) {
		packageName = 'my-rpm'
        version=jarVersion
        release=build
        os = LINUX
        
		from(jar.outputs.files) {
       		print 'copying the server jar'
            into '/apps/myapp'
            permissionGroup='root'
            user = 'root'
        }
        from('scripts/start')
       {
       	into '/apps/scripts'
       	fileMode = 777
       	permissionGroup='root'
        user = 'root'
       }
       link('/apps/myapps/my-app-' + jarVersion + '.' + build + '.jar', '/apps/scripts/startup' , 022)
}

Can you please help me on what m i missing??? i need to create the initscript for my springboot uberjar...
i.e. i need to do ln -s /apps/myapps/my-app-1.2.3.jar /apps/scripts/startup

Post this i should be able to control my jar using this starup script...

**Comment by lbrigman124** [comment]
The first input to link is the link not the file.  Reverse the order.

**Comment by DanielThomas** [comment]
4.7.5 and later also significantly improve automatic symlink support.
