### ISSUE TITLE
nebula.rpm 4.4.0 installs symlinks with relative path

### ISSUE THREAD

**Issue by sbohrer** [nebula-plugins/gradle-ospackage-plugin#250]
Starting with nebula.rpm 4.4.0 symlinks are packaged into the rpm with a relative path which breaks my rpms.  For example if you have:

```
$ ls -l common/config/
total 0
-rw-r--r-- 1 sbohrer hbi 12 Jun 29 14:40 hello.conf
lrwxrwxrwx 1 sbohrer hbi 10 Jun 29 14:40 link.conf -> hello.conf
```

```
plugins {
  id "nebula.rpm" version "4.3.0"
}

task createRpm(type: Rpm) {
  packageName 'link-test'
  arch X86_64
  os LINUX
  user 'hbi'
  permissionGroup 'hbi'

  version project.configVersion
  release project.version

  addParentDirs = false
  includeEmptyDirs = false

  from('common/config') {
    include "**/*"
    into "/opt/local/config"
  }
}
```
With nebula.rpm version 4.3.0 I get:
```
$ rpm -qpl build/distributions/link-test-0.1-1234.x86_64.rpm
/opt/local/rgm/config/files/hello.conf
/opt/local/rgm/config/files/link.conf
```
With nebula.rpm version 4.4.0 I get:
```
$ rpm -qpl build/distributions/link-test-0.1-1234.x86_64.rpm
/opt/local/rgm/config/files/hello.conf
opt/local/rgm/config/files/link.conf
```
Note that link.conf is missing the leading / which I believe is incorrect.  I suspect the commit that is breaking things is ebc137a47f603cbbb8bc0e086381135220b6ba34 "Support symlinks by default".  I can see that with 4.3.0 link.conf ends up being a copy of hello.conf and not a symlink which is I'm sure what this commit was trying to fix, but it appears it still isn't doing the right thing.

**Comment by antonulasevich** [comment]
I am seeing a similar behavior in 4.4.0. However things are getting even more complicated if symlinks are contained in a folder to which there is also a symlink. In this case the symlink to a folder is not installed and instead becomes a copy of the folder, and also none of the symlinks are installed.

**Comment by jfbibeau** [comment]
Seeing same thing here. Symlinks created with 4.4.0 seem to only have a relative path as opposed to a full path.

I believe this was introduced in PR #228. Prior to that change, symlinks were not preserved (the target file was actually copied). But in 4.4.0 symlinks are preserved, but the source symlink is set to relative path, possible because of this line:

https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/228/files#diff-618a7a9d59f4a2003bed63bad6482fa1R16

**Comment by DanielThomas** [comment]
I’ve since gone back and rewritten the symlink code again. They’ll now relativize if they share a path within a CopySpec, otherwise they’ll be copied as regular files. Try the latest version of the plugin (4.7.5 and later).
