### ISSUE TITLE
not taking version set in gradle.taskGraph.whenReady block

### ISSUE THREAD

**Issue by shiva2991** [nebula-plugins/gradle-ospackage-plugin#253]
I am unable to get the value of version property set in `gradle.taskGraph.whenReady` block. How to get the value of version set in `gradle.taskGraph.whenReady` in `buildRpm` task?
Conditions:
Gradle version: 4.0
nebula.os-package Plugin: 2.2.0

Code snippets:
```
// --- buildscript and plugins blocks goes here -----
version = '4.1.0-RC5'
// ---- necessary functions goes here ------

buildRpm () {
println "Version in buildRpm is ${version}"
doFirst{println "Version in buildRpm is ${version}"}
doLast{println "Version in buildRpm is ${version}"}

	def rversion = ("${version}" =~ /-/).replaceAll("_")
	packageName archivesBaseName	
	version "${rversion}"
// --- some code goes here ---
}

task snapshot(dependsOn: buildRpm) {
	println "Creating a release build for Version: ${version}"
}

gradle.taskGraph.whenReady { taskGraph ->
     if (!taskGraph.hasTask(':release')) {
      version = "${version}-SNAPSHOT-${buildTime()}"
	  println "Version set to $version"
     }	 
}
```
when i run `gradle clean snapshot` the output contains
```
> Configure project :
Version in buildRpm is 4.1.0-RC5

> Task :buildRpm
Version in buildRpm is 4.1.0_RC5
Version in buildRpm is 4.1.0_RC5
```
and version output expected is `4.1.0-RC5-SNAPSHOT-05-08-2017-210216-IST`

**Comment by DanielThomas** [comment]
@shiva2991 that'd be expected, seeing as your code to configure the version for the `buildRpm task  runs when the build script is evaluated. You're better off doing everything in the `doFirst` on the task.
