### ISSUE TITLE
Use public getter for Redline RPM Builder

### ISSUE THREAD

**Issue by dchesterman** [nebula-plugins/gradle-ospackage-plugin#258]
I'm trying to configure a custom tag for an RPM I am creating and if the Redline Builder created was via a public overrideable method, a user could customize a large swath of creation behavior.  Request to move the resolution of a Builder instance to the public API.

**Comment by rpalcolea** [comment]
This was implemented in https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/259
