### ISSUE TITLE
project version becomes empty

### ISSUE THREAD

**Issue by salvianreynaldi** [nebula-plugins/gradle-ospackage-plugin#263]
I was trying this plugin, and I realized my distZip task now produce an archive without version in its name.
What is the purpose of making this empty?
Can this plugin use their own Distribution so that we don't have to make the default task version empty?

https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/546c5cd0a50fc50f4b3dab3415e4b12d42c015e3/src/main/groovy/com/netflix/gradle/plugins/application/OspackageApplicationPlugin.groovy#L52

**Comment by DanielThomas** [comment]
This is no longer the case - the plugin now uses the install task to produce the files to add to the package.
