### ISSUE TITLE
Disable includeStandardDefines

### ISSUE THREAD

**Issue by malejpavouk** [nebula-plugins/gradle-ospackage-plugin#264]
Hi,

is it possible to disable includeStandardDefines. The additional script files, which this plugin creates cause some troubles in our setup, as the scripts end up with status 127.

I believe that part of the trouble might be that pretrans msut be written in Lua: https://fedoraproject.org/wiki/Packaging:Scriptlets

Thanks!

**Comment by malejpavouk** [comment]
I've been able to get rid of scriptlet contents using the following approach:

```
task customBuildRpm(type: RpmCustom){}
build.dependsOn(customBuildRpm)


class RpmCustom extends Rpm {
    @Override
    AbstractPackagingCopyAction createCopyAction() {
        def action = new RpmCopyAction(this)
        action.includeStandardDefines = false
        return action
    }
}
```


But still the scriptlet "headers" are present. Its because unfortunanate implementation of [RpmCopyAction](https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/d151dbab30c760a1fa5ae8eb7da6de4d43b8c5cd/src/main/groovy/com/netflix/gradle/plugins/rpm/RpmCopyAction.groovy#L92-L97), which passes emtpy array to RedLine. here should be non-empty check. 

If you think this is a good idea and do not have time for this fix, let me know, I can prepare a pull request for this.

**Comment by malejpavouk** [comment]
I see that this is a known issue and even PR for this is ready: https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/254

Would it be possible to merge it?

**Comment by kgaughan** [comment]
Looks like #254 has finally been merged! I'd say you can close this now.

**Comment by malejpavouk** [comment]
cool, last question, then I close it: Do you have any timeline, when will be new version of nebula (containing this fix) released?

**Comment by kgaughan** [comment]
Me? No. Only a contributor. However, @rspieldenner would, I would say.
