### ISSUE TITLE
Release 4.6.0 is not published to repository

### ISSUE THREAD

**Issue by flozano** [nebula-plugins/gradle-ospackage-plugin#271]
In https://jcenter.bintray.com/com/netflix/nebula/gradle-ospackage-plugin/ , latest is v4.5.1.

**Comment by malejpavouk** [comment]
4.8.0 is already out

**Comment by DanielThomas** [comment]
We had a JCenter sync hiccup there. Newer versions are there as @malejpavouk mentions.
