### ISSUE TITLE
SimpleWorkResult type has been deprecated

### ISSUE THREAD

**Issue by kpb** [nebula-plugins/gradle-ospackage-plugin#273]
Version: 4.4.0

When running buildRpm, Gradle emits the following warning:

`The SimpleWorkResult type has been deprecated and is scheduled to be removed in Gradle 5.0. Please use WorkResults.didWork() instead.`

It looks like  _AbstractPackagingCopyAction.groovy_ has the line:

`return new SimpleWorkResult(true)`

A fix would be nice before the impending Gradle 5 release.

Thanks!

**Comment by cxwtc123** [comment]
We met the same issue, upgrade to v4.6.0, everything is ok for our usage.

**Comment by kpb** [comment]
The newest version of ospackage I see is 4.5.1??

**Comment by cxwtc123** [comment]
v 4.6.0.
refer:
https://plugins.gradle.org/plugin/nebula.ospackage
https://github.com/nebula-plugins/gradle-ospackage-plugin/releases

**Comment by DanielThomas** [comment]
Yep, fixed since https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v4.4.1.
