### ISSUE TITLE
AbstractPackagingCopyAction uses a deprecated Gradle method

### ISSUE THREAD

**Issue by sc1478** [nebula-plugins/gradle-ospackage-plugin#281]
We build many rpm packages that use your plugin.  We do try to keep current with new Gradle versions.  Since 4.x came out we've been getting deprecation warnings in our builds: 

`The SimpleWorkResult type has been deprecated and is scheduled to be removed in Gradle 5.0. Please use WorkResults.didWork() instead.`

None of our build.gradle scripts use the SimpleWorkResult type but I looked at your plugin and find it used in AbstractPackagingCopyAction. 

Please update this code so that we can use it with newer Gradle versions.

**Comment by DanielThomas** [comment]
This has been fixed since https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v4.4.1.

**Comment by sc1478** [comment]
Thanks, Danny.  I actually tried to the check source code first and I still saw SimpleWorkResult in this file, or I would not have opened the issue, I must have somehow opened the wrong version of the code.  Not sure how.

**Comment by DanielThomas** [comment]
It's still there for backwards compatibility, we have a fallback:

https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/d151dbab30c760a1fa5ae8eb7da6de4d43b8c5cd/src/main/groovy/com/netflix/gradle/plugins/packaging/AbstractPackagingCopyAction.groovy#L41-L55
