### ISSUE TITLE
ospackage plugin 4.9.3 can not be resolved from gradle build

### ISSUE THREAD

**Issue by hehondou** [nebula-plugins/gradle-ospackage-plugin#299]
A problem is occurred when I build with nebula.ospackage.
The configuration of my build.gradle is like below.
![selection_005](https://user-images.githubusercontent.com/13404915/43645094-811111a4-9763-11e8-8812-f54cd0ee4f08.png)

But when I execute ./gradlew build, the problem occured like:
![selection_006](https://user-images.githubusercontent.com/13404915/43645299-04328c66-9764-11e8-9d1c-3ab8f588e86c.png)

So I opened the link "https://plugins.gradle.org/m2/nebula/ospackage/nebula.ospackage.gradle.plugin/4.9.3/nebula.ospackage.gradle.plugin-4.9.3.jar", the web page shows like:

![selection_007](https://user-images.githubusercontent.com/13404915/43645423-6e04b9c0-9764-11e8-82e0-abbf58c92dd9.png)

**Comment by rpalcolea** [comment]
Closing this as we recommend to just upgrade to latest version of the plugin. We might not fix this release in the plugin portal as it is quite old
