### ISSUE TITLE
how to dynamically configure version in ospackage, deb or rpm task

### ISSUE THREAD

**Issue by akasolace** [nebula-plugins/gradle-ospackage-plugin#309]
Update: I also post the question on [SO](https://stackoverflow.com/questions/53097115/gradle-how-to-use-result-of-task-in-configuration-phase-plugin-ospackage)

In my gradle script I initialize variable as:
```
ext {
    ...
    my_version = "XXX"
    ...
}
```
then I have an init task that set ext.my_version by reading some files

I configured ospackage as is:
```
ospackage {
...
version project.ext.myversion
...
}
```

the problem is ospackage always consider the initial value "XXX" and not the correct one that was set by the init task.
I also tried to create a task like the one below but it also fails because it is not taken in consideration (says version not specified)

```
buildDeb {
    doLast {
        version project.ext.my_version
        link('/usr/bin/aa', '/usr/bin/aa.sh')
        postInstall "mkdir -p -m 0777 ~/.aa"
    }
}
```

Any idea how I can achieve that? Thank you in advance for your help

**Comment by chali** [comment]
Hi @akasolace, have you tried to set project version in the standard gradle way? `project.version = 'XXX'` We use that property as a default value.

**Comment by rpalcolea** [comment]
Closing this one as lack of inactivity and `project.version` could work
