### ISSUE TITLE
(Question) ospackage without "release" information possible?

### ISSUE THREAD

**Issue by apgsga-jhe** [nebula-plugins/gradle-ospackage-plugin#319]
Hi Team,
When I build an RPM using following:

```
ospackage {
	packageName = test
	version = 1.0
	//release = 1
	os = LINUX
	type = BINARY
	arch = NOARCH
....
}
```
... an RPM will be built with following name: 

> test-1.0.noarch.rpm

Which is absolutely correct.

But when installing the RPM, its version will be 

> 1.0-

Assuming we don't want to provide any Release information (not saying that it's good practice or not), is there a way to remove this last "-" ?

**Comment by rpalcolea** [comment]
Hi, ideally this shouldn't happen.

Any chance you could share a buildscript that reproduces this? 

Looking at how we assemble the name -> https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/1cdee210f9c8e99742362fde2403a048fd32a927/src/main/groovy/com/netflix/gradle/plugins/rpm/Rpm.groovy#L47

I don't expect a `-` after the version

**Comment by apgsga-jhe** [comment]
Unfortunately I can't quickly provide a sample script. In the meantime we went ahead with a release which is in our case always "1".
