### ISSUE TITLE
buildRpm doesn't include architecture in filename on Gradle 5

### ISSUE THREAD

**Issue by Str8AWay** [nebula-plugins/gradle-ospackage-plugin#324]
Upgrading from grald 4.10.X to 5.1.X causes buildRpm to no longer include the architecture in the filename.

Ex. Gradle 4 filename: foo-0.1.0.noarch.rpm
Ex. Gradle 5 filename: foo-0.1.0.rpm

**Comment by rpalcolea** [comment]
Hi @Str8AWay!

can you provide a sample project with this behavior? which version of ospackage are you using?

I created this sample project: https://github.com/rpalcolea/gradle-ospackage-rpm-test

If you clone it and run `./gradlew buildRpm` you will see the following in the build output:

```
gradle-ospackage-rpm-test git/master
❯ ls -lah build/distributions
total 8.0K
drwxr-xr-x 4 rperezalcolea  128 Apr 30 16:33 ./
drwxr-xr-x 4 rperezalcolea  128 Apr 30 16:32 ../
-rw-r--r-- 1 rperezalcolea 1.3K Apr 30 16:33 gradle-ospackage-rpm-test-1.0.0.noarch.rpm
-rw-r--r-- 1 rperezalcolea 1.3K Apr 30 16:32 gradle-ospackage-rpm-test-unspecified.noarch.rpm

```

`noarch` is part of the rpm name using Gradle 5.4.1 and latest ospackage (6.2.0)

**Comment by flozano** [comment]
We have seen similar issue when using gradle 5 and older 5.x version of the ospackage plugin. When upgrading to 6.2.1 version of this plugin, `noarch` was back.

**Comment by rpalcolea** [comment]
Closing this as it appears that this is just solved by upgrading both gradle and ospackage plugin
