### ISSUE TITLE
5.3.0-5.3.5 releases are identical

### ISSUE THREAD

**Issue by elusiveeagle** [nebula-plugins/gradle-ospackage-plugin#339]
Let me start by saying I am currently using version 6. However, as I was perusing the [releases](https://github.com/nebula-plugins/gradle-ospackage-plugin/releases) to see if there was anything new, I noticed that the 5.3.0 through 5.3.5 releases are identical. Each of these releases points to the same commit https://github.com/nebula-plugins/gradle-ospackage-plugin/commit/4cd02c2c26278435ebfda7d800c57f5ea18f93f2.

I can't imagine this would be intentional, but perhaps it was. Again, this is not really an issue for myself since I'm using version 6, but I thought I'd report it for awareness.

I'm also not really sure how you'd go about fixing this since these releases are already 'out in the wild'. At a minimum I suppose it could serve as a helpful reminder to be mindful of what commits are selected when you publish a new release. :)

**Comparisons showing that each 5.3.X release is identical to 5.3.0**
https://github.com/nebula-plugins/gradle-ospackage-plugin/compare/v5.3.0...v5.3.1
https://github.com/nebula-plugins/gradle-ospackage-plugin/compare/v5.3.0...v5.3.2
https://github.com/nebula-plugins/gradle-ospackage-plugin/compare/v5.3.0...v5.3.3
https://github.com/nebula-plugins/gradle-ospackage-plugin/compare/v5.3.0...v5.3.4
https://github.com/nebula-plugins/gradle-ospackage-plugin/compare/v5.3.0...v5.3.5

**Quick links to each 5.3.X release**
https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v5.3.5
https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v5.3.4
https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v5.3.3
https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v5.3.2
https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v5.3.1
https://github.com/nebula-plugins/gradle-ospackage-plugin/releases/tag/v5.3.0

**Comment by rpalcolea** [comment]
Hi

Thanks for the heads up

We had some issues with out release pipeline that ended up needing to trigger new releases for the same commit.

We will definitely keep this in mind next time and sorry for the inconvenience
