### ISSUE TITLE
Archive name is not configurable

### ISSUE THREAD

**Issue by kai-github** [nebula-plugins/gradle-ospackage-plugin#34]
This is a very helpful plugin, thanks for providing this plugin. 
Just a suggestion regarding the archive properties, it would be good if the archiveName property as well as the archString property are made configurable, as some project may use their own naming conventions for archive files. Thanks!
(com.netflix.gradle.plugins.deb.Deb)

**Comment by kgeis** [comment]
I am successfully setting archiveName in an Rpm task in 2.2.0.

**Comment by bmuschko** [comment]
Sounds like it is supported now. I am going to close the issue. @kai-github Please upgrade to a later version of the plugin.
