### ISSUE TITLE
requires() to support $(uname -r) parameter

### ISSUE THREAD

**Issue by jpfreyen** [nebula-plugins/gradle-ospackage-plugin#363]
This:

```
buildRpm {
        requires('bar', '2.2', EQUAL)
}
```

at times isn't ideal because we are hard-coding a version and sometimes we just want a way to retrieve the value and compare it.

Specifically for requiring packages like "kernel-devel" in Redhat, I want:

`requires('kernel-devel, $(uname -r), EQUAL)`

Unfortunately this doesn't work, the resulting .rpm package complains it cannot find the right package version.  However, normal command-line works fine:

`yum install kernel-devel-$(uname -r)`

I want this gradle module to be able to do this, but I'm not sure if this is a feature request or it was expected to work but there is a bug.

**Comment by DanielThomas** [comment]
That yum example is a subshell executing that command. From Gradle you'd need to exec out. Better still depending on your distribution there's a file in `/etc` that has the information you're after, `redhat-release`, `lsb-release`, `os-release` etc.
