### ISSUE TITLE
8.4.0 produces "corrupt" tar files in deb packages

### ISSUE THREAD

**Issue by linsomniac** [nebula-plugins/gradle-ospackage-plugin#378]
On Ubuntu 18.04 system (built on 16.04), we get the following message when we try to install a deb package that has as it's longest filename path as 134 characters:

    error processing archive /var/cache/apt/archives/PACKAGE.deb (--unpack):
    corrupted filesystem tarfile - corrupted package archive

when using version 8.4.0.  If we use 8.3.1, the resulting package is able to be installed.

I'm guessing this is related to change 6c36b7b https://github.com/nebula-plugins/gradle-ospackage-plugin/commit/6c36b7bfa889bc772d7219be3c106615ab51dffc which added the following line:

    maker.setTarLongFileMode('posix')

If I extract the .deb file and do "tar tf" on "data.tar.gz", everything seems fine, but dpkg cannot install it.

In looking into the tar file, I see that the one that works has empty "pax headers" on the tar headers for the longer file names, where the one that does not has pax headers with "path" elements.

I'm guessing that however the debian tools extract the files, they are unable to process, at least in Ubuntu 18.04, files that have the pax headers.

Note: We have been using this build process, with packages that have longer than 100 character file paths, for years, without problems, prior to the 8.4.0 version.

**Comment by rpalcolea** [comment]
Hi!

Thanks for bringing this up

We rolled back the change and released 8.4.1

**Comment by linsomniac** [comment]
Thank you!
