### ISSUE TITLE
Packages with links are never considered UP-TO-DATE

### ISSUE THREAD

**Issue by ljohnston** [nebula-plugins/gradle-ospackage-plugin#38]
Any package that configures a link is always considered out of date. 
```
$ ./gradlew buildDeb --info
<snip>
Executing task ':buildDeb' (up-to-date check took 0.073 secs) due to:
  Value of input property 'allLinks' has changed for task ':buildDeb'
<snip>
```
The above is the case even if the link configuration has not changed since the previous build.

Thanks

**Comment by bmuschko** [comment]
@ljohnston Can you please check with the latest version of the plugin? It should be working from our perspective.

**Comment by bmuschko** [comment]
I am going to close this issue. Should be working with the latest version of the plugin. Please reopen if you still experience the issue.
