### ISSUE TITLE
Minor: fix directory permissions in examples

### ISSUE THREAD

**Issue by gallardo** [nebula-plugins/gradle-ospackage-plugin#380]
The example provided in [the wiki](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/RPM-Plugin#directories) is misleading:

> # Directories
> Specifies directory that should be created within package.
>
>     directory(String path, int permissions)
> E.g.
>
>     directory('/some/dir')
>     directory('/some/dir', 644)

This won't be interpreted as octal. The example could be improved:

    directory('/some/dir', 0644)

(See reported and closed bug: https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/152)

**Comment by rpalcolea** [comment]
Hi! thanks for reporting this.

This should be fixed now in the example
