### ISSUE TITLE
requires(package1).or(package2) does not work

### ISSUE THREAD

**Issue by algorithmWithPython** [nebula-plugins/gradle-ospackage-plugin#382]
in this doc https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin, it mentions that requires can be used as:
requires(String packageName, String version, int flag).or(String packageName, String version, int flag)

In my code, I did:
requires('openjdk11-xxx').or('jdk1.8-xxx')

When I tried to install the rpm, I got:
`
sudo rpm -Uvh xxx-4.18.1.xxx.1.2.1-xxx.noarch.rpm
error: Failed dependencies:
        openjdk11-xxx is needed by xxx-0:4.18.1.xxx.1.2.1-xxx99.noarch
`

I do have jdk1.8-xxx installed on this test machine.

**Comment by algorithmWithPython** [comment]
ok. I am using rpm instead of Deb. from the doc, rpm seems do not support or. If this is the case, you can close this one. thanks.

**Comment by pf-malandry** [comment]
What is missing to include the support into the RPM plugin?

**Comment by DanielThomas** [comment]
There's no such capability in RPM, `Requires` are an explicit request for a package. That request can be for a virtual package however, so in this case those packages likely provide something like `java-jdk` or similar you can request:

https://stackoverflow.com/a/2139685/364206

**Comment by pf-malandry** [comment]
Respectfully, I understand this may not be a priority but RPM does support a OR concept.

[RPM Manual - Boolean Dependencies](https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html)

**Comment by DanielThomas** [comment]
Huh, so there is. Someone would need to implement it in redline and here. That would have to be a contribution, we don't use RPM here.
