### ISSUE TITLE
No .git directory found

### ISSUE THREAD

**Issue by raphattack** [nebula-plugins/gradle-ospackage-plugin#388]
I have a project using this plugin to package to `.deb` and `.rpm`. Works great on my other machine, just got a new laptop.

Did a `git clone` and tried running the below command:
```
$ ./gradlew clean build buildDeb buildRpm -PbuildNumber=local

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/raphattack/IdeaProjects/parser/build.gradle.kts' line: 13

* What went wrong:
No .git directory found!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 666ms
```

**Line 13:**
```
val git: Grgit = Grgit.open()
```

Both the `.git` and `.gradle` folders are in the same root:
```
$ ls -alF
.git/
.gitignore
.gradle/
README.md
bin/
build.gradle.kts
conf/
gradle/
gradlew*
gradlew.bat
log/
ospackage/
settings.gradle.kts
src/
```

**Comment by DanielThomas** [comment]
That's not related to ospackage. For what it's worth `Grgit.open()` uses the working directory if the directory isn't specified - https://ajoberstar.org/grgit/grgit-open.html. You might try `Grgit.open(dir: rootProject.projectDir)`.
