### ISSUE TITLE
"license" property not working for deb plugin

### ISSUE THREAD

**Issue by syvaidya** [nebula-plugins/gradle-ospackage-plugin#389]
Deb Task documentation mentions `license` property for the task:

https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin

But providing any value for the same has no impact on the generated .deb file.

**Comment by DanielThomas** [comment]
That's a copy of the properties from `SystemPackagingTask` which is shared between the deb and rpm tasks. There is a `copyright` file standard for Debian that could be generated, but unlikely to be needed by most - I'll remove it from the docs.

**Comment by syvaidya** [comment]
Thanks @DanielThomas
