### ISSUE TITLE
User and group not set for rpm?

### ISSUE THREAD

**Issue by xml44** [nebula-plugins/gradle-ospackage-plugin#39]
Hi,

I cannot get generated RPM to set correct user and group for installed files. In ospackage I have:

    from(jar.outputs.files) { 
        user 'someuser'
        permissionGroup 'somegroup'
        fileMode = 0440
        into 'lib'
    }

I create user and group in preInstall, but when the jar file is installed permissions are set ok, but user is my username and group is root.

Am I missing something or is this a bug? (I use version plugin 1.9.3)

Thanks

**Comment by bmuschko** [comment]
I think this is an issue in the Redline library. For more information have a look at issue #102.
