### ISSUE TITLE
rpm failed to install on FIPS enabled RHEL node

### ISSUE THREAD

**Issue by vinodharari** [nebula-plugins/gradle-ospackage-plugin#412]
Hi Team, I using plugin 'com.netflix.nebula:gradle-ospackage-plugin:6.1.1'

while installing rpm on  FIPS enabled RHEL node I am getting error
Error: Transaction test error:
package <pkg name> does not verify: no digest

I can see below details upon checking rpm --checksig
Header SHA1 digest: OK
Payload SHA256 digest: NOTFOUND
MD5 digest: NOTFOUND

how do we solve this issue

**Comment by DanielThomas** [comment]
Start by upgrading the plugin, you're many major versions behind. The current release includes Redline 1.2.10 which supports sha256:

- https://github.com/nebula-plugins/gradle-ospackage-plugin/commit/a942e969e4a87e7120da33ca251cbe9b3d6c9d2b
- https://github.com/craigwblake/redline/commit/45494bc9718ba3385edd0c747d60b1b32da8b766
