### ISSUE TITLE
Cannot configure directory entries in ospackage extension

### ISSUE THREAD

**Issue by mricciuti** [nebula-plugins/gradle-ospackage-plugin#416]
The `directory`  entries cannot be defined in the ospackage extension, only on the rpm/deb tasks configurations:

```
buildRpm {
	directory("/directory/from/task")  // <=== OK, directory entry will be part of the produced rpm/deb
}

ospackage {
	user 'root'
	directory("/directory/from/extension")   // <=== DOES NOT WORK ; not propagated to task configuration
}
```
This will produce a RPM with following directories:
```
    RPM content details:                  [perm , user/group  ]
    ----------------------------------------------------------
    /directory/from/task                  [40755, root/root]
```

This issue has already been mentioned in other issues ( like here https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/275#issuecomment-370134690 ) , but there is no dedicated issue for it.

Plugins version: 9.1.1
Gradle version: 7.5.1

**Comment by mricciuti** [comment]
When looking at  `endVisit()` method here https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/main/src/main/groovy/com/netflix/gradle/plugins/packaging/AbstractPackagingCopyAction.groovy#L110 : 

```
void endVisit() {
        // ... 
        for (Dependency provides : task.getAllProvides()) {  // <=== merged is done between task & parent extension values
            logger.debug "adding provides on {} {}", provides.packageName, provides.version
            addProvides(provides)
        }

        task.directories.each { directory ->    /// <====  only directories defined on Task configuration are used. 
            logger.debug "adding directory {}", directory.path
            addDirectory(directory)
        }

}
```

- for some properties like  `conflicts`, `links`, `dependencies` : a call to `task.getAllXyz()` is made so that we get a merged list of values coming from the task AND the extension configuration, 
- for `directories` : only directories defined in Task configuration are user,  the ones defined on the parent extension are simply "lost"

I think we could expect to have the same behavior for `directories` as other properties, here.

**Comment by mricciuti** [comment]
this PR will fix it: https://github.com/nebula-plugins/gradle-ospackage-plugin/pull/417

**Comment by MLNW** [comment]
The mentioned PR was merged but the issue remains open
