### ISSUE TITLE
RPM can't be built if project version contains '-' character

### ISSUE THREAD

**Issue by sshcherbakov** [nebula-plugins/gradle-ospackage-plugin#49]
Hello all, 

just run into as issue when building an RPM using plugin version 1.12.2 and Gradle 1.12.
My project has '.BUILD-SNAPSHOT' in the version.
The buildRpm task fails with the message in this case:

```
12:58:10.158 [ERROR] [org.gradle.BuildExceptionReporter] > version with value: '1.1.2.9.BUILD-SNAPSHOT' contains illegal character -
...
2:58:10.164 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: version with value: '1.1.2.9.BUILD-SNAPSHOT' contains illegal character -
12:58:10.164 [ERROR] [org.gradle.BuildExceptionReporter]    at org.freecompany.redline.Builder.checkVariableContainsIllegalChars(Builder.java:229)
12:58:10.164 [ERROR] [org.gradle.BuildExceptionReporter]    at org.freecompany.redline.Builder.setPackage(Builder.java:246)
12:58:10.164 [ERROR] [org.gradle.BuildExceptionReporter]    at com.netflix.gradle.plugins.rpm.RpmCopyAction.startVisit(RpmCopyAction.groovy:54)
12:58:10.164 [ERROR] [org.gradle.BuildExceptionReporter]    at com.netflix.gradle.plugins.packaging.AbstractPackagingCopyAction.execute(AbstractPackagingCopyAction.groovy:43)
12:58:10.164 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:52)
```

Setting version explicitly to a value without '-' doesn't help:

```
ospackage {
version = '1.2.3'
```

Only if I change the main Gradle project version I get the RPM built.
Is this something that needs to be fixed?

**Comment by bmuschko** [comment]
@sshcherbakov Can you try the latest 2.2.x version of the plugin? We built in some validation for RPM versions.

**Comment by sshcherbakov** [comment]
@bmuschko it looks like the 2.2.x version is not compatible with Gradle 1.12 that we are still on:
````
A problem occurred evaluating root project 'rti-t-gfxd'.
> org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
````
It will take some time to migrate the build script to the Gradle 2.x

**Comment by bmuschko** [comment]
@sshcherbakov That is correct. We won't continue putting fixes into the 1.12.x branch. You'll need to upgrade your project.

**Comment by bmuschko** [comment]
@sshcherbakov Did you have a chance to test out the latest version? I guess we'll close the issue if we don't hear back from you.

**Comment by shollander** [comment]
@bmuschko

I am having the same problem with trying to override the project version and rpm not "seeing" the new version. I have a multi-module gradle project. When I build an individual module it works without a problem, but when I build the entire project from the top (all modules) then rpm does not get the modified version.

**Comment by DALDEI** [comment]
I have logged a bug that may be related. It seems some combination of gradle and ospacakage are 'overly aggressive' at caching. If I make a build only or script  only change it doesnt take without a clean.

As for versioning I run into confusion over the scope of properties, and trying to

**Comment by shollander** [comment]
As mentioned earlier, I had been experiencing this issue. I discovered that by using the ospackage dsl to define the version and release instead of doing it in the Rpm task fixed the problem. Seems to me that this would still be a bug that should be fixed, but at least I have a workaround.

**Comment by ajeets1978** [comment]
I am using the latest version 3.2.1, still see the same issue. Rather more than that nebula-release plugin generates -SNAPSHOTs, which is what i am trying to use for nebula-ospackage as well the same version for my RPMs. It throws an error ~ is an illegal character. Its replacing - with ~ signs :(

**Comment by farrukhnajmi** [comment]
I am using version 4.2.2 and still seeing this problem. BTW, AFAIK '-' is a valid rpm version character and I see it used in a whole bunch of rpms on my Fedora system when I do a "rpm -qa | less" command. I would be grateful for a high priority fix for this issue as it is a blocker for me. I do not have option to use workaround as versionNames are set by the customer product and I have no say in the conventions used. TIA.

**Comment by leoneves** [comment]
I'm using version 4.1.0 and has same issue.
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildRpm'.
> version with value: '1.3.14~SNAPSHOT' contains illegal character ~

**Comment by sghill** [comment]
[rpm.org's docs](http://rpm.org/max-rpm-snapshot/ch-rpm-file-format.html) state `-` is not valid for a version or release:

> The only restriction placed on the version is that it cannot contain a dash "-".

> The release can be thought of as the package's version. [...] Like the version number, the only restriction is that dashes are not allowed.

In addition to the workarounds proposed above in this thread, it's also possible to replace all the illegal characters in an auto-calculated version:

```gradle
def sanitizedVersion = version.toString().replaceAll('(~|-)', '') // or an allowable character like ':' or '+' 

ospackage {
    version sanitizedVersion
    // ...
}
```

The \~ issue mentioned in recent comments is being tracked by #213.
