### ISSUE TITLE
Any version of plugin greater than 1.12.3 crashes gradle daemon 

### ISSUE THREAD

**Issue by ngutzmann** [nebula-plugins/gradle-ospackage-plugin#60]
When i try to use any version greater than 1.12.3 in the 1.12 stream of the plugin the gradle daemon crashes. If I run the build with the --no-daemon option I get the following information:
```
[machine-name]$ ./gradlew tasks --refresh-dependencies --no-daemon
> Configuring > 0/1 projects > root project#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xb79f691b, pid=3567, tid=3074542480
#
# JRE version: 6.0_14-b08
# Java VM: Java HotSpot(TM) Server VM (14.0-b16 mixed mode linux-x86 )
# Problematic frame:
# V  [libjvm.so+0x5d991b]
#
# An error report file with more information is saved as:
# /path/to/err/hs_err_pid3567.log
#
# If you would like to submit a bug report, please visit:
#   http://java.sun.com/webapps/bugreport/crash.jsp
#
Aborted
```
I can add the hs_err_pid*.log file if you'd like but was wondering if anyone has encountered this issue before? I'd be willing to look into this myself but don't have any clues about where to start, so those would also be appreciated.

**Comment by bmuschko** [comment]
@ngutzmann Seems like the reflection hackery doesn't play well with the Gradle daemon. If we get a new version of the JDeb library that contains [this fix](https://github.com/tcurdt/jdeb/pull/183), we can easily release a new version.

**Comment by bmuschko** [comment]
Pushed a new version. That should fix it.
