### ISSUE TITLE
Question: Pre-Depend?

### ISSUE THREAD

**Issue by danveloper** [nebula-plugins/gradle-ospackage-plugin#62]
Is there a mechanism within this plugin to define a pre-dependency?

See [Declaring relationships between packages](https://www.debian.org/doc/debian-policy/ch-relationships.html) for more details on this.

**Comment by bmuschko** [comment]
This will be supported by version 2.2.1. Please see [commit](https://github.com/nebula-plugins/gradle-ospackage-plugin/commit/08ca06c2fb1550b4740b5a112019c45569792c39) for more infos.

**Comment by vasilevichra** [comment]
Could you tell me please how can I use dependencies in my build.gradle?
