### ISSUE TITLE
rpm 4.11.2 fails with "not an rpm package"

### ISSUE THREAD

**Issue by relgames** [nebula-plugins/gradle-ospackage-plugin#64]
rpm 4.11.2-3 
gradle 2.2

$ gradle clean rpm
$ rpm -qp build/distributions/test-1.0-0.noarch.rpm
error: build/distributions/test-1.0-0.noarch.rpm: headerRead failed: hdr load: BAD
error: build/distributions/test-1.0-0.noarch.rpm: not an rpm package (or package manifest)

build.gradle

```
group = 'org.relgames'
version = '1.0'
description = "test"

buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.spockframework:spock-grails-support:0.7-groovy-2.0'
        classpath 'com.netflix.nebula:gradle-ospackage-plugin:1.12.2'
    }
}

apply plugin: 'rpm'

task rpm(type: Rpm) {
    release '0'
}
```

settings.gradle

```
rootProject.name = 'test'
```

**Comment by novasbc** [comment]
I know this is old, but is it not valid to have an empty RPM?  So that I could have a package with no files of it's own, but specifies a list of dependencies.
