### ISSUE TITLE
createDirectoryEntry is not working for empty dirs

### ISSUE THREAD

**Issue by relgames** [nebula-plugins/gradle-ospackage-plugin#67]
com.netflix.nebula:gradle-ospackage-plugin:2.0.2
```
    File varDir = Files.createTempDirectory(null).toFile()
    println varDir
    from(varDir) {
        into "$baseDir/var"
        createDirectoryEntry = true
    }
    varDir.deleteOnExit();
```

Does not create var dir. 
If I put empty file into varDir it works.

**Comment by bmuschko** [comment]
The [directory assignment](https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/gradle-1.12/src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginTest.groovy#L849) should do it.

**Comment by bmuschko** [comment]
I am going to close this issue as we haven't heard back from you. Please reopen if the propose solution doesn't work for you.

**Comment by relgames** [comment]
Hi, sorry for not answering in time, directory() worked indeed.
