### ISSUE TITLE
fileType does not work for debian packages

### ISSUE THREAD

**Issue by omerozkan** [nebula-plugins/gradle-ospackage-plugin#74]
Hello

For debian packages, there is a problem config files. In the debian packages there must be `conffiles` file in control.tar.gz for configuration files. But the plugin does not create `conffiles` for configured `fileType CONFIG | NOREPLACE`

Regards

**Comment by bmuschko** [comment]
Would you be interested in working on a pull request for this?

**Comment by sghill** [comment]
Closing as duplicate of #118
