### ISSUE TITLE
apt-get not working on preinstall script

### ISSUE THREAD

**Issue by fefedao** [nebula-plugins/gradle-ospackage-plugin#75]
apt-get not working on preinstall script

**Comment by rspieldenner** [comment]
I don't believe you can do apt-get install in the preinstall script of a debian. Usually you can `require` the package and that will get it to install.

**Comment by fefedao** [comment]
I guess you are right. My intentention was to install puppet before run dpkg on my .deb, so i can install it as a service on my server os.

Thank you anyway.
