### ISSUE TITLE
'directory' construct results in invalid rpm

### ISSUE THREAD

**Issue by Jolter** [nebula-plugins/gradle-ospackage-plugin#76]
Hi,

I want my RPM to create a few empty directory when installed. Like so, in an oldfashioned rpm spec:

```
%dir /var/opt/myapp/data
```

I tried using this 

```
ospackage {
    packageName = 'foo'
}
buildRpm {
     directory('/var/opt/myapp/data', 640)
}
```

When calling `rpm -q -filesbypkg -p <myrpm>`, I get this, seemingly correct, output: 

```
foo          /var/opt/myapp/data
```

But, when installing, it fails:

```
[vagrant@guest1 share]$ sudo rpm -i foo-0.0.1.noarch.rpm
error: unpacking of archive failed on file ./var/opt/myapp/data: cpio: Archive file not in header
```

I don't see, first of all, why it tries to install the directory in ".", and secondly, why even that fails.

Any hints would be most welcome since the Plugin-Rpm.md file is not very forthcoming on the issue of directories.

**Comment by Jolter** [comment]
Anyone?

**Comment by bmuschko** [comment]
Given this [test case](https://github.com/nebula-plugins/gradle-ospackage-plugin/blob/gradle-1.12/src/test/groovy/com/netflix/gradle/plugins/rpm/RpmPluginTest.groovy#L849), it should generally work. Did you try this without setting the file mode? I think it would helpful for us if you could either extend this test case or create a new one in `RpmPluginTest.groovy`?

**Comment by Jolter** [comment]
Will give it a shot when I have time. I wonder, does the current test case test the validity of the resulting RPM?

**Comment by bmuschko** [comment]
@Jolter Not sure if the Redline RPM library has a check for something like that. You might want to poke around in their API.

**Comment by Jolter** [comment]
Hm. Would you mind giving it a shot and see if you can reproduce my problem on your machine? 

Since my error is not detected until installing the RPM, I'm not sure if using the unit test suite for this would be useful, if it doesn't validate the resulting RPM.

**Comment by Jolter** [comment]
I mean, I have to way of telling if this is 
A. a Redline bug
B. a gradle-ospackage bug
C. a problem in my environment

**Comment by Jolter** [comment]
This problem no longer seems to manifest in nebula.ospackage 3.4.0.

**Comment by zunkree** [comment]
Faced with the same issue.
