### ISSUE TITLE
Set architecture in the DEB package

### ISSUE THREAD

**Issue by davidkaya** [nebula-plugins/gradle-ospackage-plugin#77]
I would like to set the target architecture for the Debian package but I've seen that it is not implemented yet.
![screen shot 2015-01-19 at 10 38 03](https://cloud.githubusercontent.com/assets/3832960/5798432/432c4ae4-9fc7-11e4-8057-c27b0324553f.png)

Would it be possible to implement it?
Thanks a lot

**Comment by bmuschko** [comment]
Would you be interested in providing a pull request for this?

**Comment by quidryan** [comment]
Done in #95

**Comment by davidkaya** [comment]
@bmuschko If the question sounded offensive, I would like to apologise for that. I would've created a pull request if my Groovy skills were on such level that I would have confidence for implementing it.
@quidryan Thanks a lot for implementation.
