### ISSUE TITLE
Unable to use fileType in Deb tasks

### ISSUE THREAD

**Issue by jacek99** [nebula-plugins/gradle-ospackage-plugin#8]
//Upstart file for Debian, customized compared to the CentOS version
    from('src/deploy/resources/config/service/upstart/debian') {
        into '/etc/init'
        fileType = CONFIG | NOREPLACE
    }

The upstart files between Debian and CentOS are pretty different, so we need to customize it in the Debian task, not in the common ospackage.

But when I do this we get....

* What went wrong:
A problem occurred evaluating root project 'myapp'.
> No such property: CONFIG for class: org.gradle.api.internal.file.copy.CopySpecWrapper_Decorated

it works though in the rpm task....

**Comment by bmuschko** [comment]
@jacek99 It should be fixed with the lastest version of the plugin. Can you please retry?

**Comment by bmuschko** [comment]
Should be fixed. I am going to close the issue. Please reopen if you are still experiencing the issue.
