### ISSUE TITLE
Building DEB restricts shell and actions in install scripts

### ISSUE THREAD

**Issue by dparasam** [nebula-plugins/gradle-ospackage-plugin#84]
For the install scripts,
- one cannot change default shell to anything other than "/bin/sh".  This is fine if the user supplied code is dash-compatible (default on Debian systems).  However it would be good to have this configurable, e.g., to specify "#!/bin/bash" if the user code is only bash-compatible.
- the plugin assumes that user supplied code for preInstall and postInstall scripts are always invoked with "install" parameter.  It would be good to provide flexibility for adding other actions such as "configure", "abort-remove" etc

The simplest fix is to make the preinst.ftl, postinst.ftl, prerm.ftl, postrm.ftl scripts free-form, i.e., just insert the user-supplied code verbatim (the user could then also specify the shell of choice in the she-bang line)

**Comment by tbroyer** [comment]
I'd just like to be able to provide the "control directory", containing the control scripts, to jDeb; without any specific processing by the plugin.
I understand though this might not play well with RPMs, and the ability to create both kinds of packages from the same configuration; but maybe scripts in the 'control directory" could take priority over commands configured from the build file, or fail the build if there's a conflict (e.g. if there are `preInstall` commands then there must **not** be a `preinst` script)

**Comment by dparasam** [comment]
Below is a patch for what I initially suggested.  Instead of changing the shell to hard-coded /bin/bash, it would be nice to allow that to be configured as well.



    diff --git a/src/main/resources/deb/postinst.ftl b/src/main/resources/deb/postins
    index b52c13f..16b336f 100644
    --- a/src/main/resources/deb/postinst.ftl
    +++ b/src/main/resources/deb/postinst.ftl
    @@ -1,22 +1,5 @@
    -#!/bin/sh -e
    +#!/bin/bash
    -ec() {
    -    echo "\$@" >&2
    -    "\$@"
    -}
    -
    -case "\$1" in
    -    configure)
    -        <% dirs.each{ dir -> %>
    -        <% if (dir['owner']) { %>
    -            ec install -o <%= dir['owner'] %> -d <%= dir['name'] %>
    -        <% } else { %>
    -            ec install -d <%= dir['name'] %>
    -        <% } %>
    -        <% } %>
    -
    -        <% commands.each {command -> %>
    -        <%= command %>
    -        <% } %>
    -        ;;
    -esac
    +<% commands.each {command -> %>
    +<%= command %>
    +<% } %>
    diff --git a/src/main/resources/deb/postrm.ftl b/src/main/resources/deb/postrm.ft
    index 18c889f..16b336f 100644
    --- a/src/main/resources/deb/postrm.ftl
    +++ b/src/main/resources/deb/postrm.ftl
    @@ -1,4 +1,4 @@
    -#!/bin/sh -e
    +#!/bin/bash

     <% commands.each {command -> %>
     <%= command %>
    diff --git a/src/main/resources/deb/preinst.ftl b/src/main/resources/deb/preinst.
    index ffd64af..16b336f 100644
    --- a/src/main/resources/deb/preinst.ftl
    +++ b/src/main/resources/deb/preinst.ftl
    @@ -1,9 +1,5 @@
    -#!/bin/sh -e
    +#!/bin/bash

    -case "\$1" in
    -    install)
    -        <% commands.each {command -> %>
    -        <%= command %>
    -        <% } %>
    -        ;;
    -esac
    +<% commands.each {command -> %>
    +<%= command %>
    +<% } %>
    diff --git a/src/main/resources/deb/prerm.ftl b/src/main/resources/deb/prerm.ftl
    index 18c889f..16b336f 100644
    --- a/src/main/resources/deb/prerm.ftl
    +++ b/src/main/resources/deb/prerm.ftl
    @@ -1,4 +1,4 @@
    -#!/bin/sh -e
    +#!/bin/bash

     <% commands.each {command -> %>
     <%= command %>

**Comment by bedge** [comment]
I'd vote for switching to bash and/or cutting out some of the template restrictions too. I mentioned the same problem here as well.
https://github.com/nebula-plugins/gradle-ospackage-plugin/issues/119

The above patch is a step in the right direction.

+1

**Comment by sghill** [comment]
@dparasam @tbroyer This plugin now supports providing the complete maintainer script file with the `*File` directives documented [here](https://github.com/nebula-plugins/gradle-ospackage-plugin/wiki/Deb-Plugin#scripts). 

While not exactly what was outlined in this issue, I think it achieves the same goal -- could you confirm this works for your use case?

**Comment by tbroyer** [comment]
That'd have worked for me, yes.
