### ISSUE TITLE
validate version for buildDeb

### ISSUE THREAD

**Issue by coryb** [nebula-plugins/gradle-ospackage-plugin#85]
from the manpage: http://manpages.ubuntu.com/manpages/quantal/man5/deb-version.5.html

              The upstream-version  may  contain  only  alphanumerics  ("A-Za-
              z0-9")  and  the  characters . + - : ~ (full stop, plus, hyphen,
              colon, tilde) and should start with a digit.  

So:

* version must start with digit
* version can only contain [A-Za-z0-9.+:~-]

**Comment by bmuschko** [comment]
Would you be interested in providing a pull request for this?

**Comment by quidryan** [comment]
@bmuschko, can you implement this?

**Comment by bmuschko** [comment]
@quidryan Sure thing!
