### ISSUE TITLE
Task name clash?

### ISSUE THREAD

**Issue by andredasilvapinto** [nebula-plugins/gradle-ospackage-plugin#9]
I'm getting task name clashes when I apply the rpm plugin in a project that already defines a clean or assemble tasks. Considering these are quite common task names, shouldn't the rpm plugin use different names to avoid this kind of problems?

This is the error message:

    A problem occurred evaluating root project 'vert.x'.
    Cannot add task ':clean' as a task with that name already exists.

**Comment by bmuschko** [comment]
The Vert.x project doesn't use Gradle anymore as it's build tool. Seems like they switched to Maven.
