### ISSUE TITLE
Debian files do not have parent directories when built on Windows

### ISSUE THREAD

**Issue by jfiore-ibm** [nebula-plugins/gradle-ospackage-plugin#93]
When a debian file is built on Windows, it does not include the parent directories of the files in the debian file.
This is not the case when built on Linux. Because of this, debian files built on Windows are not able to be installed. 
This is fixed in JDeb 1.1 (https://github.com/tcurdt/jdeb/issues/95) 

Could the 2.2.x branch be upgraded to JDeb 1.1 or later (ideally the latest)?

**Comment by bmuschko** [comment]
The `gradle-2.2` branch already has the latest JDeb version. I am still waiting on a bunch of changes to be reviewed. After that, we'll release.

**Comment by jfiore-ibm** [comment]
Great! I will look forward to that being released soon. Thanks for the quick response!
