### ISSUE TITLE
Version 2.2.1 forces dependency on default-jre | java6-runtime 

### ISSUE THREAD

**Issue by jfiore-ibm** [nebula-plugins/gradle-ospackage-plugin#96]
In version 2.2.1 of this package, the upgrade of Jdeb to 1.4 adds a default dependency of "default-jre | java6-runtime"

If you aren't using debs with dependencies (or if your target system doesn't have either of those dependencies available), this will break your debians.
There is a workaround for JDeb in that JDeb will only use those code-defaults if the Depends: is not specified in the control file.
If Depends is specified but empty, it will not insert those defaults.
The existing control.ftl in this project only outputs a "Depends:" if there are non-empty dependencies specified.

Fortunately, the gradle-ospackage-plugin project generates the control file by rendering a template loaded from the classpath.
So we worked around this in our project by getting our own control.ftl on the classpath prior to the one included in this project.
We then modified it to remove the conditional around the "depends" part.
i.e. we added the following file to our `buildSrc/src/main/resources/deb/control.ftl`:
```
Source: ${name}
Section: ${section}
Priority: optional
Maintainer: ${author}
Uploaders: ${author}
Version: ${version}-${release}
Standards-Version: 3.8.3
Package: ${name}
Provides: ${provides}
Homepage: ${url}
Architecture: ${arch}<% if (multiArch) { %>
Multi-Arch: ${multiArch}<% } %>
Distribution: unstable
Depends: ${depends}
Description: ${summary}
 ${description}
```
This has fixed the problem for us. 
I don't know if this is the best solution, but I imagine others may be experiencing it also.

**Comment by bmuschko** [comment]
@jfiore-ibm Is that an issue you could raise with the [JDeb project](https://github.com/tcurdt/jdeb)? Seems like it should be fixed there if I understand the problem correctly.

**Comment by bmuschko** [comment]
@jfiore-ibm Any chance you got around to raising an issue for the JDeb project?

**Comment by jfiore-ibm** [comment]
@bmuschko I have not had a chance yet. Will try to get to it today. Sorry.

**Comment by rspieldenner** [comment]
Yeah this needs to be fixed in jdeb. An empty Depends block may corrupt the package index on a system.

**Comment by jfiore-ibm** [comment]
@rspieldenner added the issue in JDeb: https://github.com/tcurdt/jdeb/issues/208
Sorry I never got around to it until after you already did it.
Thanks for doing that.
