### ISSUE TITLE
How to publish rpm/deb to any repository?

### ISSUE THREAD

**Issue by fedotxxl** [nebula-plugins/gradle-ospackage-plugin#97]
Hello
Can you provide config which allows to publish rpm/deb to appropriate repository?

**Comment by fedotxxl** [comment]
Found working configuration - https://github.com/rackerlabs/cf-flume-sink/blob/b7fe8e50da2231ceaef5ff6baea3866ca767c24e/cf-sink/build.gradle

**Comment by bedge** [comment]
@fedotxxl 
Thanks for the link, that sample is extremely useful for cargo-culting.
