### ISSUE TITLE
Is it possible to exclude dependencies from rpm/deb files?

### ISSUE THREAD

**Issue by fedotxxl** [nebula-plugins/gradle-ospackage-plugin#98]
90% of rpm/deb file size is public dependencies. My idea is to exclude them from rpm/deb file and download them when rpm is installed. 

What do you think? What's the best way to implement it?

**Comment by bmuschko** [comment]
From my perspective, you will want to make a RPM/Deb file self-contained. Generally speaking if you want to implement this behavior, you'd have to take care yourself of excluding external libraries. There's no direct support for this functionality in the plugin.

**Comment by bmuschko** [comment]
We haven't heard back from you. I am going to close this issue. Feel free to reopen if needed.
